def DAS428_958_02_MAR_21_DAS_lado_derecho():
  set_safety_mode_transition_hardness(1)
  modbus_add_signal("192.168.10.45", 255, 187, 1, "postrnas_m187", False)
  modbus_set_signal_update_frequency("postrnas_m187", 10)
  modbus_add_signal("192.168.10.45", 255, 289, 1, "ini_cambro_m289", False)
  modbus_set_signal_update_frequency("ini_cambro_m289", 10)
  modbus_add_signal("192.168.10.45", 255, 290, 0, "fin_cambro_m290", False)
  modbus_set_signal_update_frequency("fin_cambro_m290", 10)
  modbus_add_signal("192.168.10.45", 255, 291, 1, "outputbroc_m291", False)
  modbus_set_signal_update_frequency("outputbroc_m291", 10)
  modbus_add_signal("192.168.10.45", 255, 292, 0, "fciclocarr_m292", False)
  modbus_set_signal_update_frequency("fciclocarr_m292", 10)
  modbus_add_signal("192.168.10.45", 255, 7, 1, "avancarrusel_m7", False)
  modbus_set_signal_update_frequency("avancarrusel_m7", 10)
  modbus_add_signal("192.168.10.45", 255, 252, 1, "pose2_m252", False)
  modbus_set_signal_update_frequency("pose2_m252", 10)
  modbus_add_signal("192.168.10.45", 255, 253, 1, "pose3_m253", False)
  modbus_set_signal_update_frequency("pose3_m253", 10)
  modbus_add_signal("192.168.10.45", 255, 254, 1, "pose4_m254", False)
  modbus_set_signal_update_frequency("pose4_m254", 10)
  modbus_add_signal("192.168.10.45", 255, 441, 1, "finciclo_m441", False)
  modbus_set_signal_update_frequency("finciclo_m441", 10)
  modbus_add_signal("192.168.10.45", 255, 442, 1, "finciclo_m442", False)
  modbus_set_signal_update_frequency("finciclo_m442", 10)
  modbus_add_signal("192.168.10.45", 255, 443, 1, "finciclo_m443", False)
  modbus_set_signal_update_frequency("finciclo_m443", 10)
  modbus_add_signal("192.168.10.45", 255, 503, 0, "homecobot_m503", False)
  modbus_set_signal_update_frequency("homecobot_m503", 10)
  modbus_add_signal("192.168.10.45", 255, 288, 1, "cargar_run_m288", False)
  modbus_set_signal_update_frequency("cargar_run_m288", 10)
  modbus_add_signal("192.168.10.45", 255, 287, 0, "desactiver_m288", False)
  modbus_set_signal_update_frequency("desactiver_m288", 10)
  modbus_add_signal("192.168.10.45", 255, 183, 0, "eje7home_m183", False)
  modbus_set_signal_update_frequency("eje7home_m183", 10)
  modbus_add_signal("192.168.10.45", 255, 444, 1, "finciclo_m444", False)
  modbus_set_signal_update_frequency("finciclo_m444", 10)
  modbus_add_signal("192.168.10.45", 255, 381, 0, "pat1_m381", False)
  modbus_set_signal_update_frequency("pat1_m381", 10)
  modbus_add_signal("192.168.10.45", 255, 382, 0, "pat2_m382", False)
  modbus_set_signal_update_frequency("pat2_m382", 10)
  modbus_add_signal("192.168.10.45", 255, 383, 0, "pat3_m383", False)
  modbus_set_signal_update_frequency("pat3_m383", 10)
  modbus_add_signal("192.168.10.45", 255, 384, 0, "pat4_m384", False)
  modbus_set_signal_update_frequency("pat4_m384", 10)
  modbus_add_signal("192.168.10.45", 255, 385, 0, "pat5_m385", False)
  modbus_set_signal_update_frequency("pat5_m385", 10)
  modbus_add_signal("192.168.10.45", 255, 386, 0, "pat6_m386", False)
  modbus_set_signal_update_frequency("pat6_m386", 10)
  modbus_add_signal("192.168.10.45", 255, 387, 0, "pat7_m387", False)
  modbus_set_signal_update_frequency("pat7_m387", 10)
  modbus_add_signal("192.168.10.45", 255, 388, 0, "pat8_m388", False)
  modbus_set_signal_update_frequency("pat8_m388", 10)
  modbus_add_signal("192.168.10.45", 255, 389, 0, "pat9_m389", False)
  modbus_set_signal_update_frequency("pat9_m389", 10)
  modbus_add_signal("192.168.10.45", 255, 390, 0, "pat10_m390", False)
  modbus_set_signal_update_frequency("pat10_m390", 10)
  modbus_add_signal("192.168.10.45", 255, 391, 0, "pat11_m391", False)
  modbus_set_signal_update_frequency("pat11_m391", 10)
  modbus_add_signal("192.168.10.45", 255, 392, 0, "pat12_m392", False)
  modbus_set_signal_update_frequency("pat12_m392", 10)
  modbus_add_signal("192.168.10.45", 255, 401, 0, "inipat1_m401", False)
  modbus_set_signal_update_frequency("inipat1_m401", 10)
  modbus_add_signal("192.168.10.45", 255, 402, 0, "inipat2_m402", False)
  modbus_set_signal_update_frequency("inipat2_m402", 10)
  modbus_add_signal("192.168.10.45", 255, 403, 0, "inipat3_m403", False)
  modbus_set_signal_update_frequency("inipat3_m403", 10)
  modbus_add_signal("192.168.10.45", 255, 404, 0, "inipat4_m404", False)
  modbus_set_signal_update_frequency("inipat4_m404", 10)
  modbus_add_signal("192.168.10.45", 255, 405, 0, "inipat5_m405", False)
  modbus_set_signal_update_frequency("inipat5_m405", 10)
  modbus_add_signal("192.168.10.45", 255, 406, 0, "inipat6_m406", False)
  modbus_set_signal_update_frequency("inipat6_m406", 10)
  modbus_add_signal("192.168.10.45", 255, 407, 0, "inipat7_m407", False)
  modbus_set_signal_update_frequency("inipat7_m407", 10)
  modbus_add_signal("192.168.10.45", 255, 408, 0, "inipat8_m408", False)
  modbus_set_signal_update_frequency("inipat8_m408", 10)
  modbus_add_signal("192.168.10.45", 255, 409, 0, "inipat9_m409", False)
  modbus_set_signal_update_frequency("inipat9_m409", 10)
  modbus_add_signal("192.168.10.45", 255, 410, 0, "inipat10_m410", False)
  modbus_set_signal_update_frequency("inipat10_m410", 10)
  modbus_add_signal("192.168.10.45", 255, 411, 0, "inipat11_m411", False)
  modbus_set_signal_update_frequency("inipat11_m411", 10)
  modbus_add_signal("192.168.10.45", 255, 412, 0, "inipat12_m412", False)
  modbus_set_signal_update_frequency("inipat12_m412", 10)
  modbus_add_signal("192.168.10.45", 255, 430, 0, "modeloDer_m430", False)
  modbus_set_signal_update_frequency("modeloDer_m430", 10)
  modbus_add_signal("192.168.10.45", 255, 380, 1, "mensaje_m380", False)
  modbus_set_signal_update_frequency("mensaje_m380", 10)
  modbus_add_signal("192.168.10.45", 255, 379, 0, "respues_m379", False)
  modbus_set_signal_update_frequency("respues_m379", 10)
  modbus_add_signal("192.168.10.45", 255, 251, 1, "pose1_m251", False)
  modbus_set_signal_update_frequency("pose1_m251", 10)
  modbus_set_runstate_dependent_choice("postrnas_m187",0)
  modbus_set_runstate_dependent_choice("ini_cambro_m289",0)
  modbus_set_runstate_dependent_choice("outputbroc_m291",0)
  modbus_set_runstate_dependent_choice("avancarrusel_m7",0)
  modbus_set_runstate_dependent_choice("pose2_m252",0)
  modbus_set_runstate_dependent_choice("pose3_m253",0)
  modbus_set_runstate_dependent_choice("pose4_m254",0)
  modbus_set_runstate_dependent_choice("finciclo_m441",0)
  modbus_set_runstate_dependent_choice("finciclo_m442",0)
  modbus_set_runstate_dependent_choice("finciclo_m443",0)
  modbus_set_runstate_dependent_choice("cargar_run_m288",0)
  modbus_set_runstate_dependent_choice("finciclo_m444",0)
  modbus_set_runstate_dependent_choice("mensaje_m380",0)
  modbus_set_runstate_dependent_choice("pose1_m251",0)
  set_gravity([0.0, 0.0, 9.82])
  set_tool_communication(False, 115200, 0, 1, 1.5, 3.5)
  set_tool_output_mode(0)
  set_tool_digital_output_mode(0, 1)
  set_tool_digital_output_mode(1, 1)
  set_tool_voltage(0)
  step_count_98e4103b_4832_4b77_a5c9_0e7482fdadeb = 0
  thread Step_Counter_Thread_8bf7e2c5_dc05_4eac_92ee_54103faaffcd():
    while (True):
      step_count_98e4103b_4832_4b77_a5c9_0e7482fdadeb = step_count_98e4103b_4832_4b77_a5c9_0e7482fdadeb + 1
      sync()
    end
  end
  run Step_Counter_Thread_8bf7e2c5_dc05_4eac_92ee_54103faaffcd()
  set_standard_analog_input_domain(0, 1)
  set_standard_analog_input_domain(1, 1)
  set_tool_analog_input_domain(0, 1)
  set_tool_analog_input_domain(1, 1)
  set_analog_outputdomain(0, 0)
  set_analog_outputdomain(1, 0)
  set_input_actions_to_default()
  set_runstate_standard_digital_outputs([2])
  set_runstate_configurable_digital_outputs([1])
  set_runstate_standard_digital_output_to_value(2, 1)
  set_runstate_configurable_digital_output_to_value(1, 1)
  set_tcp(p[4.109330471764039E-4,-0.21829828276152607,0.037994196120996,1.5580092985761962,-0.12546870791316503,0.12120248426608284])
  set_payload(1.5)
  global contador=0
  global Pallet_1_cnt_1=1
  global i_var_1=0
  global Pallet_1_cnt=1
  global Line_1=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global Line_2=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global Line_3=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global Line_4=p[-0.2932874787951964,0.3932288129452105,0.013749459185886714,0.019478391032120013,-0.0350876085014595,1.5300278925331599]
  global Line_5=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global Plane_1=p[-0.4357649673792705,0.3571224276764373,-0.011331751409534768,-0.03455953496512708,-0.012487423981114925,3.103751116092306]
  global Plane_2=p[-0.4823864034329737,0.3302516442079689,0.014283714098506706,0.017125077458443067,0.05770060098903715,-2.9134709732588786]
  global Plane_3=p[0.003678615545088639,0.4082921331082374,0.10477407557236007,-2.072177303174012E-4,7.379081343290108E-4,-6.424400645467977E-4]
  global Plane_4=p[-0.4500206307677429,-0.2823718146925442,-0.4767416657426552,0.013278190059218174,0.013334473770785706,1.8479691991032237]
  global Plano_patron1=p[-0.7699005610122596,0.304894434078545,0.0420369514744936,-0.0031270356010209216,1.7180543614697593E-4,-3.508888786211572E-5]
  global Point_13=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global Point_3=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global Point_8=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global Punto_prot_1=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global Punto_seg_der=p[0.23741638234469645,0.3587772222537799,0.42419077585740217,0.818517054876345,1.4216436941132238,1.005041187710707]
  global pisp_958=p[-0.41395442210486977,-0.2082168853247176,0.041553466664982,0.014014788518713659,0.01101911827984854,1.569193423241601]
  rtde_set_watchdog("speed_slider_mask", 10.0, "ignore")
  global Linea1_A_p=p[-.476229995495, -.221400000646, .080998203500, 2.026301919954, -2.392879390801, -.020840852347]
  global Linea1_A_q=[0.14380319800537403, -1.7129904950396817, 2.4141921898996173, -0.7058823359214559, -4.563135215284003, -0.00460850310699179]
  global Linea1_B_p=p[-.679349465105, -.221300898247, .080411608011, 2.026301951639, -2.392879375034, -.020840862659]
  global Linea1_B_q=[0.09076446308384334, -1.4001926101755604, 2.096443938099947, -0.700814896836861, -4.61626233837509, -0.0041144368880150495]
  global Linea1_C_p=p[-.704534367525, -.220853327749, .080142840293, 2.026301965631, -2.392879367217, -.020840869024]
  global Linea1_C_q=[0.08599134704219757, -1.3650956535369119, 2.0528147068559726, -0.6922748966640047, -4.621028689651424, -0.004079646991149488]
  global Linea1_D_p=p[-.907518787648, -.220332204194, .080644557739, 2.026301997330, -2.392879348504, -.020840881430]
  global Linea1_D_q=[0.06276293153983481, -1.091301309136636, 1.6565363529240713, -0.5697607137014327, -4.644070508698315, -0.003971392555989439]
  global Linea1_E_p=p[-.933182028781, -.220332204002, .080091450136, 2.026302001815, -2.392879346341, -.020840884120]
  global Linea1_E_q=[0.06074259634431911, -1.0556867834273191, 1.600634758365807, -0.5494715559180054, -4.646052141174379, -0.003968096385253972]
  global Linea1_F_p=p[-1.136070764074, -.220200949091, .080219797209, 2.026302018147, -2.392879338346, -.020840893414]
  global Linea1_F_q=[0.04822552943116065, -0.7488163335815479, 1.0693662766671288, -0.3250641595514523, -4.658059986134556, -0.004011756794231047]
  def calculate_point_to_move_towards(feature, direction, position_distance):
    local posDir=[direction[0], direction[1], direction[2]]
    if (norm(posDir) < 1e-6):
      return get_target_waypoint()
    end
    local direction_vector_normalized=normalize(posDir)
    local displacement_pose=p[direction_vector_normalized[0] * position_distance,direction_vector_normalized[1] * position_distance,direction_vector_normalized[2] * position_distance,0,0,0]
    local wanted_displacement_in_base_frame=pose_sub(pose_trans(feature, displacement_pose), feature)
    return pose_add(get_target_waypoint(), wanted_displacement_in_base_frame)
  end
  global Linea2_A_p=p[-.474582569199, .184453796229, .081010655673, 2.026309015281, -2.392844205549, -.020866418254]
  global Linea2_A_q=[-1.0116578878088234, -1.762749824487635, 2.4524088623654414, -0.6960806083567199, -5.7185638234892275, 0.0020130340835589067]
  global Linea2_B_p=p[-.677479020395, .185069458116, .080033764426, 2.026309050501, -2.392844210621, -.020866408927]
  global Linea2_B_q=[-0.6572084961072129, -1.4242339065955179, 2.1266811884943024, -0.7073672021333515, -5.364250974021548, -5.106618895460713E-4]
  global Linea2_C_p=p[-.703111782642, .185207152951, .080706126066, 2.026309066347, -2.392844212982, -.020866404461]
  global Linea2_C_q=[-0.6288671701046571, -1.3879242299905243, 2.080504950183902, -0.6974325694769963, -5.335902301378799, -6.69283927678066E-4]
  global Linea2_D_p=p[-.906150491750, .185294451334, .081029816483, 2.026309091004, -2.392844208354, -.020866406787]
  global Linea2_D_q=[-0.46668798977790527, -1.1075788750292856, 1.6814295832395203, -0.5783998657040392, -5.173550681011877, -0.001541947699652546]
  global Linea2_E_p=p[-.931211518276, .185988285538, .081374961685, 2.026303253874, -2.392840334076, -.020877623337]
  global Linea2_E_q=[-0.4529793541408331, -1.0730131297922298, 1.625899480709978, -0.557424460013789, -5.159802027745, -0.0016167535381867992]
  global Linea2_F_p=p[-1.134160960705, .186610310410, .081262059556, 2.026309143482, -2.392844198602, -.020866412668]
  global Linea2_F_q=[-0.3622041833237333, -0.7659724656345759, 1.0987111164025682, -0.3371407804922901, -5.068535832171082, -0.0021648706664549877]
  global Home3_p=p[-.850182153427, -.000000001054, .211319941039, -2.029706048810, 2.396843749609, .006593444086]
  global Home3_q=[-0.2508712563283524, -1.32118636682587, 1.7236419957383333, -0.39530717300436535, -4.957384713543316, -0.003346356527782035]
  global Linea3_A_p=p[-.483980872628, -.387033209968, .081049619290, -2.029718132120, 2.396836058480, .006539318202]
  global Linea3_A_q=[0.5143757890743901, -1.495057159481707, 2.2023411677350317, -0.7002230818596313, -4.192660385869312, 0.0024117787737427676]
  global Linea3_B_p=p[-.686975456027, -.386566071325, .081205257720, -2.029718156986, 2.396836053299, .006539361887]
  global Linea3_B_q=[0.35986166877844195, -1.2681950373856115, 1.916512554735208, -0.6415789741675519, -4.347120491741422, 0.0013179030531871305]
  global Linea3_C_p=p[-.712354061666, -.386033104629, .080583561326, -2.029718161575, 2.396836048499, .006539366140]
  global Linea3_C_q=[0.34557956312306537, -1.2383791509130742, 1.8755897451544996, -0.6304933098048053, -4.361386535361566, 0.0012201029610059422]
  global Linea3_D_p=p[-.915145695718, -.385549707387, .081730567138, -2.029718187384, 2.396836029506, .006539390147]
  global Linea3_D_q=[0.26373779080447013, -0.9902476931311712, 1.4863728044860909, -0.48951932747484506, -4.442968863550595, 6.060919226767998E-4]
  global Linea3_E_p=p[-.940448297915, -.385681985601, .081142470582, -2.029718193144, 2.396836022025, .006539397034]
  global Linea3_E_q=[0.25623715170917427, -0.9560768208764641, 1.4300717025205183, -0.4673975223681346, -4.450421872507805, 5.468029782866674E-4]
  global Linea3_F_p=p[-1.144266639833, -.385382616041, .081232847122, -2.029718199196, 2.396836013045, .006539406743]
  global Linea3_F_q=[0.2069508266751292, -0.6336056420305951, 0.8505695911384539, -0.2104192928451427, -4.499068433422416, 1.1335294307635024E-4]
  global Linea4_A_p=p[-.483349788271, .019133185970, .080413260871, -2.029706156948, 2.396843727542, .006593523255]
  global Linea4_A_q=[-0.6083609647283303, -1.8491607177998297, 2.508781022257942, -0.6506766877109564, -5.315140146897352, -0.006455752746111543]
  global Linea4_B_p=p[-.685405345385, .019216016482, .080605411160, -2.029706198064, 2.396843720095, .006593553911]
  global Linea4_B_q=[-0.3668720655964215, -1.4571475315744635, 2.1604050554737952, -0.6958388159675053, -5.073880300414354, -0.00379199837799149]
  global Linea4_C_p=p[-.711768401648, .019559793406, .080904090997, -2.029706252347, 2.396843636983, .006593581602]
  global Linea4_C_q=[-0.34962302775901843, -1.416353296204817, 2.111286147959993, -0.6875839998543505, -5.056628585047181, -0.0036373596678203057]
  global Linea4_D_p=p[-.914580300154, .019800824119, .080702641078, -2.029706247501, 2.396843670347, .006593582159]
  global Linea4_D_q=[-0.25502943755154917, -1.1225464208935811, 1.701966591620236, -0.5723775418058246, -4.9618762912182355, -0.0028915480853139996]
  global Linea4_E_p=p[-.939798807859, .020700910827, .080125714480, -2.029706250804, 2.396843664829, .006593585086]
  global Linea4_E_q=[-0.24786404134425943, -1.0862161019978132, 1.6460425634030225, -0.5528020492471519, -4.954674977872823, -0.0028436355394596546]
  global Linea4_F_p=p[-1.143007512073, .020923542347, .080361056646, -2.029706268179, 2.396843636814, .006593600008]
  global Linea4_F_q=[-0.19670834559854455, -0.7743888492473978, 1.1125146525836174, -0.33120940233183394, -4.903027543140608, -0.002571548256728562]
  global Linea5_A_p=p[-.663777936722, -.510056013896, .080074817758, 3.111613141107, -.392104259374, .008659076091]
  global Linea5_A_q=[0.2657106893704153, -1.148110214471835, 1.7438587855907386, -0.5841302758158697, -5.926804323304033, -0.0024226644150573406]
  global Linea5_B_p=p[-1.154197202818, -.507910812668, .080255967102, -2.646643527512, 1.679995846414, .000741631796]
  global Linea5_B_q=[0.2326977553802316, -0.511451916452792, 0.6165105933730453, -0.08883587483085797, -5.078040440032844, -0.006501132400630105]
  global Precambio_broca_p=p[.000830370305, .461517540512, .287521124194, -.221784750204, -3.131955254916, .000429460883]
  global Precambio_broca_q=[-2.1838225298159477, -2.0964618902985066, 2.243453456263678, -0.13436505871461257, -5.342774534909408, -0.004043449473680738]
  global Dejar_broca_p=p[.000823895762, .461515687097, .012951720949, -.221812511419, -3.131977617574, .000372127747]
  global Dejar_broca_q=[-2.183495316599444, -1.7678482895328447, 2.6170152878959705, -0.837583231698904, -5.343897117921112, -0.0023471751717600853]
  def Quitar_broca():
    $ 1577 "Quitar_broca" "noBreak"
    $ 1578 "Quitar_broca"
    $ 1579 "barrenos_hechos≔barrenos_hechos+1"
    global barrenos_hechos=barrenos_hechos+1
    $ 1580 "If barrenos_hechos≟14 or cambiar_broca≟ True "
    if (barrenos_hechos == 14  or  cambiar_broca ==   True  ):
      $ 1581 "'Codigo de quitar broca'"
      # 'Codigo de quitar broca'
      $ 1582 "MoveL"
      $ 1583 "Direction: Base Z+"
      global move_thread_flag_1583=0
      thread move_thread_1583():
        enter_critical
        move_thread_flag_1583 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.3)
        movel(towardsPos, a=1.2, v=0.25)
        move_thread_flag_1583 = 2
        exit_critical
      end
      move_thread_flag_1583 = 0
      move_thread_han_1583 = run move_thread_1583()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1583 > 1):
          join move_thread_han_1583
          $ 1584 "Until (distance)"
          break
        end
        sync()
      end
      $ 1585 "If eje7≟3"
      if (eje7 == 3):
        $ 1586 "Precambio_broca" "breakAfter"
        movel(Precambio_broca_p, a=1.2, v=0.25)
      end
      $ 1587 "Precambio_broca" "breakAfter"
      movel(Precambio_broca_p, a=1.2, v=0.25)
      $ 1588 "Dejar_broca" "breakAfter"
      movel(Dejar_broca_p, a=0.1, v=0.09)
      $ 1589 "Set outputbroc_m291=Encender"
      modbus_set_output_signal("outputbroc_m291", True)
      $ 1590 "Wait: 4.0"
      sleep(4.0)
      $ 1591 "Set outputbroc_m291=Apagar"
      modbus_set_output_signal("outputbroc_m291", False)
      $ 1592 "Wait: 0.5"
      sleep(0.5)
      $ 1593 "Wait fciclocarr_m292=LO"
      while (modbus_get_signal_status("fciclocarr_m292") == True):
        sync()
      end
      $ 1594 "Wait: 0.5"
      sleep(0.5)
      $ 1595 "MoveL"
      $ 1596 "Precambio_broca" "breakAfter"
      movel(Precambio_broca_p, a=0.1, v=0.09)
      $ 1597 "Set avancarrusel_m7=Encender"
      modbus_set_output_signal("avancarrusel_m7", True)
      $ 1598 "Wait: 1.0"
      sleep(1.0)
      $ 1599 "Set avancarrusel_m7=Apagar"
      modbus_set_output_signal("avancarrusel_m7", False)
      $ 1600 "Wait: 0.1"
      sleep(0.1)
    end
  end
  def Poner_broca():
    $ 1601 "Poner_broca" "noBreak"
    $ 1602 "Poner_broca"
    $ 1603 "If cambiar_broca≟ True  or iniciando_prog≟ True "
    if (cambiar_broca ==   True    or  iniciando_prog ==   True  ):
      $ 1604 "'Codigo de poner broca'"
      # 'Codigo de poner broca'
      $ 1605 "Set ini_cambro_m289=Apagar"
      modbus_set_output_signal("ini_cambro_m289", False)
      $ 1606 "MoveL"
      $ 1607 "Precambio_broca" "breakAfter"
      movel(Precambio_broca_p, a=1.2, v=0.25)
      $ 1608 "Popup: Cambia a las siguientes brocas"
      popup("Cambia a las siguientes brocas", "Advertencia", True, False, blocking=True)
      $ 1609 "Dejar_broca" "breakAfter"
      movel(Dejar_broca_p, a=0.1, v=0.09)
      $ 1610 "Set ini_cambro_m289=Encender"
      modbus_set_output_signal("ini_cambro_m289", True)
      $ 1611 "Wait: 4.0"
      sleep(4.0)
      $ 1612 "Set ini_cambro_m289=Apagar"
      modbus_set_output_signal("ini_cambro_m289", False)
      $ 1613 "Wait: 0.5"
      sleep(0.5)
      $ 1614 "Wait fciclocarr_m292=LO"
      while (modbus_get_signal_status("fciclocarr_m292") == True):
        sync()
      end
      $ 1615 "Wait: 0.5"
      sleep(0.5)
      $ 1616 "MoveL"
      $ 1617 "Precambio_broca" "breakAfter"
      movel(Precambio_broca_p, a=0.1, v=0.09)
      $ 1618 "barrenos_hechos≔0"
      global barrenos_hechos=0
      $ 1619 "iniciando_prog≔ False "
      global iniciando_prog=  False  
      $ 1620 "cambiar_broca≔ False "
      global cambiar_broca=  False  
    end
    $ 1621 "If barrenos_hechos≟14"
    if (barrenos_hechos == 14):
      $ 1622 "If cambiar_broca≟ False "
      if (cambiar_broca ==   False  ):
        $ 1623 "'Codigo de poner broca'"
        # 'Codigo de poner broca'
        $ 1624 "Set ini_cambro_m289=Apagar"
        modbus_set_output_signal("ini_cambro_m289", False)
        $ 1625 "MoveL"
        $ 1626 "Precambio_broca" "breakAfter"
        movel(Precambio_broca_p, a=1.2, v=0.25)
        $ 1627 "Dejar_broca" "breakAfter"
        movel(Dejar_broca_p, a=0.1, v=0.09)
        $ 1628 "Set ini_cambro_m289=Encender"
        modbus_set_output_signal("ini_cambro_m289", True)
        $ 1629 "Wait: 4.0"
        sleep(4.0)
        $ 1630 "Set ini_cambro_m289=Apagar"
        modbus_set_output_signal("ini_cambro_m289", False)
        $ 1631 "Wait: 0.5"
        sleep(0.5)
        $ 1632 "Wait fciclocarr_m292=LO"
        while (modbus_get_signal_status("fciclocarr_m292") == True):
          sync()
        end
        $ 1633 "Wait: 0.5"
        sleep(0.5)
        $ 1634 "MoveL"
        $ 1635 "Precambio_broca" "breakAfter"
        movel(Precambio_broca_p, a=0.1, v=0.09)
        $ 1636 "barrenos_hechos≔0"
        global barrenos_hechos=0
      else:
        $ 1637 "Else" "noBreak"
        $ 1638 "'Codigo de poner broca'"
        # 'Codigo de poner broca'
        $ 1639 "Set ini_cambro_m289=Apagar"
        modbus_set_output_signal("ini_cambro_m289", False)
        $ 1640 "MoveL"
        $ 1641 "Precambio_broca" "breakAfter"
        movel(Precambio_broca_p, a=1.2, v=0.25)
        $ 1642 "Popup: Cambia a las siguientes brocas"
        popup("Cambia a las siguientes brocas", "Advertencia", True, False, blocking=True)
        $ 1643 "Dejar_broca" "breakAfter"
        movel(Dejar_broca_p, a=0.1, v=0.09)
        $ 1644 "Set ini_cambro_m289=Encender"
        modbus_set_output_signal("ini_cambro_m289", True)
        $ 1645 "Wait: 4.0"
        sleep(4.0)
        $ 1646 "Set ini_cambro_m289=Apagar"
        modbus_set_output_signal("ini_cambro_m289", False)
        $ 1647 "Wait: 0.5"
        sleep(0.5)
        $ 1648 "Wait fciclocarr_m292=LO"
        while (modbus_get_signal_status("fciclocarr_m292") == True):
          sync()
        end
        $ 1649 "Wait: 0.5"
        sleep(0.5)
        $ 1650 "MoveL"
        $ 1651 "Precambio_broca" "breakAfter"
        movel(Precambio_broca_p, a=0.1, v=0.09)
        $ 1652 "barrenos_hechos≔0"
        global barrenos_hechos=0
        $ 1653 "iniciando_prog≔ False "
        global iniciando_prog=  False  
        $ 1654 "cambiar_broca≔ False "
        global cambiar_broca=  False  
      end
    end
  end
  while (True):
    $ 1 "Robot Program"
    $ 2 "Variables"
    $ 3 "bajada_broca≔p[0,0,-0.008,0,0,0]"
    global bajada_broca=p[0,0,-0.008,0,0,0]
    $ 4 "barrenos_menos1≔0"
    global barrenos_menos1=0
    $ 5 "barreno_actual≔0"
    global barreno_actual=0
    $ 6 "posicion≔p[0,0,300,0,0,0]"
    global posicion=p[0,0,300,0,0,0]
    $ 7 "cambiar_broca≔ False "
    global cambiar_broca=  False  
    $ 8 "barrenos_hechos≔0"
    global barrenos_hechos=0
    $ 9 "eje7≔0"
    global eje7=0
    $ 10 "Wait: 0.5"
    sleep(0.5)
    $ 11 "Home"
    $ 12 "Wait: 0.3"
    sleep(0.3)
    $ 13 "Home"
    movej([-1.6445312366589881, -1.587598620831395, 1.584064588646274, 0.01780638024567583, -5.289354288203832, -0.004017758247084835], a=1.3962634015954636, v=1.0471975511965976)
    $ 16 "Wait: 0.3"
    sleep(0.3)
    $ 17 "iniciando_prog≔ True "
    global iniciando_prog=  True  
    $ 18 "Call Poner_broca"
    Poner_broca()
    $ 19 "Posicion2"
    $ 20 "eje7≔2"
    global eje7=2
    $ 21 "Broca_1"
    $ 22 "Linea1"
    $ 23 "Marcar_puntos"
    $ 24 "MoveL"
    $ 25 "Home"
    movej([-1.6445312366589881, -1.587598620831395, 1.584064588646274, 0.01780638024567583, -5.289354288203832, -0.004017758247084835], a=1.3962634015954636, v=1.0471975511965976)
    $ 26 "Linea1_A" "breakAfter"
    movel(Linea1_A_p, a=0.5, v=0.1)
    $ 27 "Linea1_B" "breakAfter"
    movel(Linea1_B_p, a=0.5, v=0.1)
    $ 28 "Linea1_C" "breakAfter"
    movel(Linea1_C_p, a=0.5, v=0.1)
    $ 29 "Linea1_D" "breakAfter"
    movel(Linea1_D_p, a=0.5, v=0.1)
    $ 30 "Linea1_E" "breakAfter"
    movel(Linea1_E_p, a=0.5, v=0.1)
    $ 31 "Linea1_F" "breakAfter"
    movel(Linea1_F_p, a=0.5, v=0.1)
    $ 32 "AB"
    $ 33 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 34 "bajada_broca≔p[0,0,-0.008,0,0,0]"
    global bajada_broca=p[0,0,-0.008,0,0,0]
    $ 35 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 36 "barreno_actual≔0"
    global barreno_actual=0
    $ 37 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 38 "Perforacion"
      $ 39 "MoveL"
      $ 40 "internos≔interpolate_pose(Linea1_A, Linea1_B, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea1_A_p, Linea1_B_p, barreno_actual/barrenos_menos1)
      $ 41 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 42 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 43 "bajada_broca≔p[0,0,-0.008,0,0,0]"
      global bajada_broca=p[0,0,-0.008,0,0,0]
      $ 44 "bajada≔p[0,0,0.008,0,0,0]"
      global bajada=p[0,0,0.008,0,0,0]
      $ 45 "Direction: Base Z-"
      global move_thread_flag_45=0
      thread move_thread_45():
        enter_critical
        move_thread_flag_45 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.045)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_45 = 2
        exit_critical
      end
      move_thread_flag_45 = 0
      move_thread_han_45 = run move_thread_45()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_45 > 1):
          join move_thread_han_45
          $ 46 "Until (distance)"
          break
        end
        sync()
      end
      $ 47 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 48 "Direction: Base Z+"
      global move_thread_flag_48=0
      thread move_thread_48():
        enter_critical
        move_thread_flag_48 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.002)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_48 = 2
        exit_critical
      end
      move_thread_flag_48 = 0
      move_thread_han_48 = run move_thread_48()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_48 > 1):
          join move_thread_han_48
          $ 49 "Until (distance)"
          break
        end
        sync()
      end
      $ 50 "Wait: 0.3"
      sleep(0.3)
      $ 51 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 52 "Wait: 0.3"
      sleep(0.3)
      $ 53 "Loop 3 times"
      Loop_11 = 0
      while (Loop_11 < 3):
        $ 54 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 55 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 56 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 57 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.005)
        $ 58 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_11 = Loop_11 + 1
      end
      $ 59 "Direction: Base Z+"
      global move_thread_flag_59=0
      thread move_thread_59():
        enter_critical
        move_thread_flag_59 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_59 = 2
        exit_critical
      end
      move_thread_flag_59 = 0
      move_thread_han_59 = run move_thread_59()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_59 > 1):
          join move_thread_han_59
          $ 60 "Until (distance)"
          break
        end
        sync()
      end
      $ 61 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 62 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 63 "Call Quitar_broca"
      Quitar_broca()
      $ 64 "Call Poner_broca"
      Poner_broca()
    end
    $ 65 "CD"
    $ 66 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 67 "bajada_broca≔p[0,0,-0.008,0,0,0]"
    global bajada_broca=p[0,0,-0.008,0,0,0]
    $ 68 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 69 "barreno_actual≔0"
    global barreno_actual=0
    $ 70 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 71 "Perforacion"
      $ 72 "MoveL"
      $ 73 "internos≔interpolate_pose(Linea1_C, Linea1_D, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea1_C_p, Linea1_D_p, barreno_actual/barrenos_menos1)
      $ 74 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 75 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 76 "bajada_broca≔p[0,0,-0.008,0,0,0]"
      global bajada_broca=p[0,0,-0.008,0,0,0]
      $ 77 "bajada≔p[0,0,0.008,0,0,0]"
      global bajada=p[0,0,0.008,0,0,0]
      $ 78 "Direction: Base Z-"
      global move_thread_flag_78=0
      thread move_thread_78():
        enter_critical
        move_thread_flag_78 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.045)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_78 = 2
        exit_critical
      end
      move_thread_flag_78 = 0
      move_thread_han_78 = run move_thread_78()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_78 > 1):
          join move_thread_han_78
          $ 79 "Until (distance)"
          break
        end
        sync()
      end
      $ 80 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 81 "Direction: Base Z+"
      global move_thread_flag_81=0
      thread move_thread_81():
        enter_critical
        move_thread_flag_81 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.002)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_81 = 2
        exit_critical
      end
      move_thread_flag_81 = 0
      move_thread_han_81 = run move_thread_81()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_81 > 1):
          join move_thread_han_81
          $ 82 "Until (distance)"
          break
        end
        sync()
      end
      $ 83 "Wait: 0.3"
      sleep(0.3)
      $ 84 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 85 "Wait: 0.3"
      sleep(0.3)
      $ 86 "Loop 3 times"
      Loop_14 = 0
      while (Loop_14 < 3):
        $ 87 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 88 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 89 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 90 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.005)
        $ 91 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_14 = Loop_14 + 1
      end
      $ 92 "Direction: Base Z+"
      global move_thread_flag_92=0
      thread move_thread_92():
        enter_critical
        move_thread_flag_92 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_92 = 2
        exit_critical
      end
      move_thread_flag_92 = 0
      move_thread_han_92 = run move_thread_92()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_92 > 1):
          join move_thread_han_92
          $ 93 "Until (distance)"
          break
        end
        sync()
      end
      $ 94 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 95 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 96 "Call Quitar_broca"
      Quitar_broca()
      $ 97 "Call Poner_broca"
      Poner_broca()
    end
    $ 98 "EF"
    $ 99 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 100 "bajada_broca≔p[0,0,-0.008,0,0,0]"
    global bajada_broca=p[0,0,-0.008,0,0,0]
    $ 101 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 102 "barreno_actual≔0"
    global barreno_actual=0
    $ 103 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 104 "Perforacion"
      $ 105 "MoveL"
      $ 106 "internos≔interpolate_pose(Linea1_E, Linea1_F, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea1_E_p, Linea1_F_p, barreno_actual/barrenos_menos1)
      $ 107 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 108 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 109 "bajada_broca≔p[0,0,-0.008,0,0,0]"
      global bajada_broca=p[0,0,-0.008,0,0,0]
      $ 110 "bajada≔p[0,0,0.008,0,0,0]"
      global bajada=p[0,0,0.008,0,0,0]
      $ 111 "Direction: Base Z-"
      global move_thread_flag_111=0
      thread move_thread_111():
        enter_critical
        move_thread_flag_111 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.045)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_111 = 2
        exit_critical
      end
      move_thread_flag_111 = 0
      move_thread_han_111 = run move_thread_111()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_111 > 1):
          join move_thread_han_111
          $ 112 "Until (distance)"
          break
        end
        sync()
      end
      $ 113 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 114 "Direction: Base Z+"
      global move_thread_flag_114=0
      thread move_thread_114():
        enter_critical
        move_thread_flag_114 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.002)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_114 = 2
        exit_critical
      end
      move_thread_flag_114 = 0
      move_thread_han_114 = run move_thread_114()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_114 > 1):
          join move_thread_han_114
          $ 115 "Until (distance)"
          break
        end
        sync()
      end
      $ 116 "Wait: 0.3"
      sleep(0.3)
      $ 117 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 118 "Wait: 0.3"
      sleep(0.3)
      $ 119 "Loop 3 times"
      Loop_16 = 0
      while (Loop_16 < 3):
        $ 120 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 121 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 122 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 123 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.005)
        $ 124 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_16 = Loop_16 + 1
      end
      $ 125 "Direction: Base Z+"
      global move_thread_flag_125=0
      thread move_thread_125():
        enter_critical
        move_thread_flag_125 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_125 = 2
        exit_critical
      end
      move_thread_flag_125 = 0
      move_thread_han_125 = run move_thread_125()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_125 > 1):
          join move_thread_han_125
          $ 126 "Until (distance)"
          break
        end
        sync()
      end
      $ 127 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 128 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 129 "Call Quitar_broca"
      Quitar_broca()
      $ 130 "Call Poner_broca"
      Poner_broca()
    end
    $ 131 "Popup: Linea1 con chica Terminada!"
    popup("Linea1 con chica Terminada!", "Mensaje", False, False, blocking=True)
    $ 132 "Linea2"
    $ 133 "Marcar_puntos"
    $ 134 "MoveL"
    $ 135 "Linea2_A" "breakAfter"
    movel(Linea2_A_p, a=0.5, v=0.1)
    $ 136 "Linea2_B" "breakAfter"
    movel(Linea2_B_p, a=0.5, v=0.1)
    $ 137 "Linea2_C" "breakAfter"
    movel(Linea2_C_p, a=0.5, v=0.1)
    $ 138 "Linea2_D" "breakAfter"
    movel(Linea2_D_p, a=0.5, v=0.1)
    $ 139 "Linea2_E" "breakAfter"
    movel(Linea2_E_p, a=0.5, v=0.1)
    $ 140 "Linea2_F" "breakAfter"
    movel(Linea2_F_p, a=0.5, v=0.1)
    $ 141 "AB"
    $ 142 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 143 "bajada_broca≔p[0,0,-0.008,0,0,0]"
    global bajada_broca=p[0,0,-0.008,0,0,0]
    $ 144 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 145 "barreno_actual≔0"
    global barreno_actual=0
    $ 146 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 147 "Perforacion"
      $ 148 "MoveL"
      $ 149 "internos≔interpolate_pose(Linea2_A, Linea2_B, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea2_A_p, Linea2_B_p, barreno_actual/barrenos_menos1)
      $ 150 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 151 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 152 "bajada_broca≔p[0,0,-0.008,0,0,0]"
      global bajada_broca=p[0,0,-0.008,0,0,0]
      $ 153 "bajada≔p[0,0,0.008,0,0,0]"
      global bajada=p[0,0,0.008,0,0,0]
      $ 154 "Direction: Base Z-"
      global move_thread_flag_154=0
      thread move_thread_154():
        enter_critical
        move_thread_flag_154 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.045)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_154 = 2
        exit_critical
      end
      move_thread_flag_154 = 0
      move_thread_han_154 = run move_thread_154()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_154 > 1):
          join move_thread_han_154
          $ 155 "Until (distance)"
          break
        end
        sync()
      end
      $ 156 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 157 "Direction: Base Z+"
      global move_thread_flag_157=0
      thread move_thread_157():
        enter_critical
        move_thread_flag_157 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.002)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_157 = 2
        exit_critical
      end
      move_thread_flag_157 = 0
      move_thread_han_157 = run move_thread_157()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_157 > 1):
          join move_thread_han_157
          $ 158 "Until (distance)"
          break
        end
        sync()
      end
      $ 159 "Wait: 0.3"
      sleep(0.3)
      $ 160 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 161 "Wait: 0.3"
      sleep(0.3)
      $ 162 "Loop 3 times"
      Loop_2 = 0
      while (Loop_2 < 3):
        $ 163 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 164 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 165 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 166 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.005)
        $ 167 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_2 = Loop_2 + 1
      end
      $ 168 "Direction: Base Z+"
      global move_thread_flag_168=0
      thread move_thread_168():
        enter_critical
        move_thread_flag_168 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_168 = 2
        exit_critical
      end
      move_thread_flag_168 = 0
      move_thread_han_168 = run move_thread_168()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_168 > 1):
          join move_thread_han_168
          $ 169 "Until (distance)"
          break
        end
        sync()
      end
      $ 170 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 171 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 172 "Call Quitar_broca"
      Quitar_broca()
      $ 173 "Call Poner_broca"
      Poner_broca()
    end
    $ 174 "CD"
    $ 175 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 176 "bajada_broca≔p[0,0,-0.008,0,0,0]"
    global bajada_broca=p[0,0,-0.008,0,0,0]
    $ 177 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 178 "barreno_actual≔0"
    global barreno_actual=0
    $ 179 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 180 "Perforacion"
      $ 181 "MoveL"
      $ 182 "internos≔interpolate_pose(Linea2_C, Linea2_D, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea2_C_p, Linea2_D_p, barreno_actual/barrenos_menos1)
      $ 183 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 184 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 185 "bajada_broca≔p[0,0,-0.008,0,0,0]"
      global bajada_broca=p[0,0,-0.008,0,0,0]
      $ 186 "bajada≔p[0,0,0.008,0,0,0]"
      global bajada=p[0,0,0.008,0,0,0]
      $ 187 "Direction: Base Z-"
      global move_thread_flag_187=0
      thread move_thread_187():
        enter_critical
        move_thread_flag_187 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.045)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_187 = 2
        exit_critical
      end
      move_thread_flag_187 = 0
      move_thread_han_187 = run move_thread_187()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_187 > 1):
          join move_thread_han_187
          $ 188 "Until (distance)"
          break
        end
        sync()
      end
      $ 189 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 190 "Direction: Base Z+"
      global move_thread_flag_190=0
      thread move_thread_190():
        enter_critical
        move_thread_flag_190 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.002)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_190 = 2
        exit_critical
      end
      move_thread_flag_190 = 0
      move_thread_han_190 = run move_thread_190()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_190 > 1):
          join move_thread_han_190
          $ 191 "Until (distance)"
          break
        end
        sync()
      end
      $ 192 "Wait: 0.3"
      sleep(0.3)
      $ 193 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 194 "Wait: 0.3"
      sleep(0.3)
      $ 195 "Loop 3 times"
      Loop_5 = 0
      while (Loop_5 < 3):
        $ 196 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 197 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 198 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 199 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.005)
        $ 200 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_5 = Loop_5 + 1
      end
      $ 201 "Direction: Base Z+"
      global move_thread_flag_201=0
      thread move_thread_201():
        enter_critical
        move_thread_flag_201 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_201 = 2
        exit_critical
      end
      move_thread_flag_201 = 0
      move_thread_han_201 = run move_thread_201()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_201 > 1):
          join move_thread_han_201
          $ 202 "Until (distance)"
          break
        end
        sync()
      end
      $ 203 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 204 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 205 "Call Quitar_broca"
      Quitar_broca()
      $ 206 "Call Poner_broca"
      Poner_broca()
    end
    $ 207 "EF"
    $ 208 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 209 "bajada_broca≔p[0,0,-0.008,0,0,0]"
    global bajada_broca=p[0,0,-0.008,0,0,0]
    $ 210 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 211 "barreno_actual≔0"
    global barreno_actual=0
    $ 212 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 213 "Perforacion"
      $ 214 "MoveL"
      $ 215 "internos≔interpolate_pose(Linea2_E, Linea2_F, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea2_E_p, Linea2_F_p, barreno_actual/barrenos_menos1)
      $ 216 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 217 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 218 "bajada_broca≔p[0,0,-0.008,0,0,0]"
      global bajada_broca=p[0,0,-0.008,0,0,0]
      $ 219 "bajada≔p[0,0,0.008,0,0,0]"
      global bajada=p[0,0,0.008,0,0,0]
      $ 220 "Direction: Base Z-"
      global move_thread_flag_220=0
      thread move_thread_220():
        enter_critical
        move_thread_flag_220 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.045)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_220 = 2
        exit_critical
      end
      move_thread_flag_220 = 0
      move_thread_han_220 = run move_thread_220()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_220 > 1):
          join move_thread_han_220
          $ 221 "Until (distance)"
          break
        end
        sync()
      end
      $ 222 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 223 "Direction: Base Z+"
      global move_thread_flag_223=0
      thread move_thread_223():
        enter_critical
        move_thread_flag_223 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.002)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_223 = 2
        exit_critical
      end
      move_thread_flag_223 = 0
      move_thread_han_223 = run move_thread_223()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_223 > 1):
          join move_thread_han_223
          $ 224 "Until (distance)"
          break
        end
        sync()
      end
      $ 225 "Wait: 0.3"
      sleep(0.3)
      $ 226 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 227 "Wait: 0.3"
      sleep(0.3)
      $ 228 "Loop 3 times"
      Loop_9 = 0
      while (Loop_9 < 3):
        $ 229 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 230 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 231 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 232 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.005)
        $ 233 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_9 = Loop_9 + 1
      end
      $ 234 "Direction: Base Z+"
      global move_thread_flag_234=0
      thread move_thread_234():
        enter_critical
        move_thread_flag_234 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_234 = 2
        exit_critical
      end
      move_thread_flag_234 = 0
      move_thread_han_234 = run move_thread_234()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_234 > 1):
          join move_thread_han_234
          $ 235 "Until (distance)"
          break
        end
        sync()
      end
      $ 236 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 237 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 238 "If barreno_actual≥barrenos_menos1"
      if (barreno_actual >= barrenos_menos1):
        $ 239 "cambiar_broca≔ True "
        global cambiar_broca=  True  
      end
      $ 240 "Call Quitar_broca"
      Quitar_broca()
      $ 241 "Call Poner_broca"
      Poner_broca()
    end
    $ 242 "Popup: Linea2 con chica Terminada!"
    popup("Linea2 con chica Terminada!", "Mensaje", False, False, blocking=True)
    $ 243 "Broca_2"
    $ 244 "Linea1"
    $ 245 "Marcar_puntos"
    $ 246 "MoveL"
    $ 247 "Linea1_A" "breakAfter"
    movel(Linea1_A_p, a=0.5, v=0.1)
    $ 248 "Linea1_B" "breakAfter"
    movel(Linea1_B_p, a=0.5, v=0.1)
    $ 249 "Linea1_C" "breakAfter"
    movel(Linea1_C_p, a=0.5, v=0.1)
    $ 250 "Linea1_D" "breakAfter"
    movel(Linea1_D_p, a=0.5, v=0.1)
    $ 251 "Linea1_E" "breakAfter"
    movel(Linea1_E_p, a=0.5, v=0.1)
    $ 252 "Linea1_F" "breakAfter"
    movel(Linea1_F_p, a=0.5, v=0.1)
    $ 253 "AB"
    $ 254 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 255 "bajada_broca≔p[0,0,-0.012,0,0,0]"
    global bajada_broca=p[0,0,-0.012,0,0,0]
    $ 256 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 257 "barreno_actual≔0"
    global barreno_actual=0
    $ 258 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 259 "Perforacion"
      $ 260 "MoveL"
      $ 261 "internos≔interpolate_pose(Linea1_A, Linea1_B, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea1_A_p, Linea1_B_p, barreno_actual/barrenos_menos1)
      $ 262 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 263 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 264 "bajada_broca≔p[0,0,-0.012,0,0,0]"
      global bajada_broca=p[0,0,-0.012,0,0,0]
      $ 265 "bajada≔p[0,0,0.012,0,0,0]"
      global bajada=p[0,0,0.012,0,0,0]
      $ 266 "Direction: Base Z-"
      global move_thread_flag_266=0
      thread move_thread_266():
        enter_critical
        move_thread_flag_266 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.045)
        movel(towardsPos, a=0.015, v=0.01)
        move_thread_flag_266 = 2
        exit_critical
      end
      move_thread_flag_266 = 0
      move_thread_han_266 = run move_thread_266()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_266 > 1):
          join move_thread_han_266
          $ 267 "Until (distance)"
          break
        end
        sync()
      end
      $ 268 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 269 "Direction: Base Z+"
      global move_thread_flag_269=0
      thread move_thread_269():
        enter_critical
        move_thread_flag_269 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_269 = 2
        exit_critical
      end
      move_thread_flag_269 = 0
      move_thread_han_269 = run move_thread_269()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_269 > 1):
          join move_thread_han_269
          $ 270 "Until (distance)"
          break
        end
        sync()
      end
      $ 271 "Wait: 0.3"
      sleep(0.3)
      $ 272 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 273 "Wait: 0.3"
      sleep(0.3)
      $ 274 "Loop 2 times"
      Loop_46 = 0
      while (Loop_46 < 2):
        $ 275 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 276 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 277 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 278 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.005)
        $ 279 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_46 = Loop_46 + 1
      end
      $ 280 "Direction: Base Z+"
      global move_thread_flag_280=0
      thread move_thread_280():
        enter_critical
        move_thread_flag_280 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_280 = 2
        exit_critical
      end
      move_thread_flag_280 = 0
      move_thread_han_280 = run move_thread_280()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_280 > 1):
          join move_thread_han_280
          $ 281 "Until (distance)"
          break
        end
        sync()
      end
      $ 282 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 283 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 284 "Call Quitar_broca"
      Quitar_broca()
      $ 285 "Call Poner_broca"
      Poner_broca()
    end
    $ 286 "CD"
    $ 287 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 288 "bajada_broca≔p[0,0,-0.012,0,0,0]"
    global bajada_broca=p[0,0,-0.012,0,0,0]
    $ 289 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 290 "barreno_actual≔0"
    global barreno_actual=0
    $ 291 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 292 "Perforacion"
      $ 293 "MoveL"
      $ 294 "internos≔interpolate_pose(Linea1_C, Linea1_D, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea1_C_p, Linea1_D_p, barreno_actual/barrenos_menos1)
      $ 295 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 296 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 297 "bajada_broca≔p[0,0,-0.012,0,0,0]"
      global bajada_broca=p[0,0,-0.012,0,0,0]
      $ 298 "bajada≔p[0,0,0.012,0,0,0]"
      global bajada=p[0,0,0.012,0,0,0]
      $ 299 "Direction: Base Z-"
      global move_thread_flag_299=0
      thread move_thread_299():
        enter_critical
        move_thread_flag_299 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.045)
        movel(towardsPos, a=0.015, v=0.01)
        move_thread_flag_299 = 2
        exit_critical
      end
      move_thread_flag_299 = 0
      move_thread_han_299 = run move_thread_299()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_299 > 1):
          join move_thread_han_299
          $ 300 "Until (distance)"
          break
        end
        sync()
      end
      $ 301 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 302 "Direction: Base Z+"
      global move_thread_flag_302=0
      thread move_thread_302():
        enter_critical
        move_thread_flag_302 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_302 = 2
        exit_critical
      end
      move_thread_flag_302 = 0
      move_thread_han_302 = run move_thread_302()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_302 > 1):
          join move_thread_han_302
          $ 303 "Until (distance)"
          break
        end
        sync()
      end
      $ 304 "Wait: 0.3"
      sleep(0.3)
      $ 305 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 306 "Wait: 0.3"
      sleep(0.3)
      $ 307 "Loop 2 times"
      Loop_48 = 0
      while (Loop_48 < 2):
        $ 308 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 309 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 310 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 311 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.005)
        $ 312 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_48 = Loop_48 + 1
      end
      $ 313 "Direction: Base Z+"
      global move_thread_flag_313=0
      thread move_thread_313():
        enter_critical
        move_thread_flag_313 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_313 = 2
        exit_critical
      end
      move_thread_flag_313 = 0
      move_thread_han_313 = run move_thread_313()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_313 > 1):
          join move_thread_han_313
          $ 314 "Until (distance)"
          break
        end
        sync()
      end
      $ 315 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 316 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 317 "Call Quitar_broca"
      Quitar_broca()
      $ 318 "Call Poner_broca"
      Poner_broca()
    end
    $ 319 "EF"
    $ 320 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 321 "bajada_broca≔p[0,0,-0.012,0,0,0]"
    global bajada_broca=p[0,0,-0.012,0,0,0]
    $ 322 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 323 "barreno_actual≔0"
    global barreno_actual=0
    $ 324 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 325 "Perforacion"
      $ 326 "MoveL"
      $ 327 "internos≔interpolate_pose(Linea1_E, Linea1_F, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea1_E_p, Linea1_F_p, barreno_actual/barrenos_menos1)
      $ 328 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 329 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 330 "bajada_broca≔p[0,0,-0.012,0,0,0]"
      global bajada_broca=p[0,0,-0.012,0,0,0]
      $ 331 "bajada≔p[0,0,0.012,0,0,0]"
      global bajada=p[0,0,0.012,0,0,0]
      $ 332 "Direction: Base Z-"
      global move_thread_flag_332=0
      thread move_thread_332():
        enter_critical
        move_thread_flag_332 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.045)
        movel(towardsPos, a=0.015, v=0.01)
        move_thread_flag_332 = 2
        exit_critical
      end
      move_thread_flag_332 = 0
      move_thread_han_332 = run move_thread_332()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_332 > 1):
          join move_thread_han_332
          $ 333 "Until (distance)"
          break
        end
        sync()
      end
      $ 334 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 335 "Direction: Base Z+"
      global move_thread_flag_335=0
      thread move_thread_335():
        enter_critical
        move_thread_flag_335 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_335 = 2
        exit_critical
      end
      move_thread_flag_335 = 0
      move_thread_han_335 = run move_thread_335()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_335 > 1):
          join move_thread_han_335
          $ 336 "Until (distance)"
          break
        end
        sync()
      end
      $ 337 "Wait: 0.3"
      sleep(0.3)
      $ 338 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 339 "Wait: 0.3"
      sleep(0.3)
      $ 340 "Loop 2 times"
      Loop_50 = 0
      while (Loop_50 < 2):
        $ 341 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 342 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 343 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 344 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.005)
        $ 345 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_50 = Loop_50 + 1
      end
      $ 346 "Direction: Base Z+"
      global move_thread_flag_346=0
      thread move_thread_346():
        enter_critical
        move_thread_flag_346 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_346 = 2
        exit_critical
      end
      move_thread_flag_346 = 0
      move_thread_han_346 = run move_thread_346()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_346 > 1):
          join move_thread_han_346
          $ 347 "Until (distance)"
          break
        end
        sync()
      end
      $ 348 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 349 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 350 "Call Quitar_broca"
      Quitar_broca()
      $ 351 "Call Poner_broca"
      Poner_broca()
    end
    $ 352 "Popup: Linea1 con media Terminada!"
    popup("Linea1 con media Terminada!", "Mensaje", False, False, blocking=True)
    $ 353 "Linea2"
    $ 354 "Marcar_puntos"
    $ 355 "MoveL"
    $ 356 "Linea2_A" "breakAfter"
    movel(Linea2_A_p, a=0.5, v=0.1)
    $ 357 "Linea2_B" "breakAfter"
    movel(Linea2_B_p, a=0.5, v=0.1)
    $ 358 "Linea2_C" "breakAfter"
    movel(Linea2_C_p, a=0.5, v=0.1)
    $ 359 "Linea2_D" "breakAfter"
    movel(Linea2_D_p, a=0.5, v=0.1)
    $ 360 "Linea2_E" "breakAfter"
    movel(Linea2_E_p, a=0.5, v=0.1)
    $ 361 "Linea2_F" "breakAfter"
    movel(Linea2_F_p, a=0.5, v=0.1)
    $ 362 "AB"
    $ 363 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 364 "bajada_broca≔p[0,0,-0.012,0,0,0]"
    global bajada_broca=p[0,0,-0.012,0,0,0]
    $ 365 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 366 "barreno_actual≔0"
    global barreno_actual=0
    $ 367 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 368 "Perforacion"
      $ 369 "MoveL"
      $ 370 "internos≔interpolate_pose(Linea2_A, Linea2_B, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea2_A_p, Linea2_B_p, barreno_actual/barrenos_menos1)
      $ 371 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 372 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 373 "bajada_broca≔p[0,0,-0.012,0,0,0]"
      global bajada_broca=p[0,0,-0.012,0,0,0]
      $ 374 "bajada≔p[0,0,0.012,0,0,0]"
      global bajada=p[0,0,0.012,0,0,0]
      $ 375 "Direction: Base Z-"
      global move_thread_flag_375=0
      thread move_thread_375():
        enter_critical
        move_thread_flag_375 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.045)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_375 = 2
        exit_critical
      end
      move_thread_flag_375 = 0
      move_thread_han_375 = run move_thread_375()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_375 > 1):
          join move_thread_han_375
          $ 376 "Until (distance)"
          break
        end
        sync()
      end
      $ 377 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 378 "Direction: Base Z+"
      global move_thread_flag_378=0
      thread move_thread_378():
        enter_critical
        move_thread_flag_378 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_378 = 2
        exit_critical
      end
      move_thread_flag_378 = 0
      move_thread_han_378 = run move_thread_378()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_378 > 1):
          join move_thread_han_378
          $ 379 "Until (distance)"
          break
        end
        sync()
      end
      $ 380 "Wait: 0.3"
      sleep(0.3)
      $ 381 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 382 "Wait: 0.3"
      sleep(0.3)
      $ 383 "Loop 2 times"
      Loop_34 = 0
      while (Loop_34 < 2):
        $ 384 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 385 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 386 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 387 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.005)
        $ 388 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_34 = Loop_34 + 1
      end
      $ 389 "Direction: Base Z+"
      global move_thread_flag_389=0
      thread move_thread_389():
        enter_critical
        move_thread_flag_389 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_389 = 2
        exit_critical
      end
      move_thread_flag_389 = 0
      move_thread_han_389 = run move_thread_389()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_389 > 1):
          join move_thread_han_389
          $ 390 "Until (distance)"
          break
        end
        sync()
      end
      $ 391 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 392 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 393 "Call Quitar_broca"
      Quitar_broca()
      $ 394 "Call Poner_broca"
      Poner_broca()
    end
    $ 395 "CD"
    $ 396 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 397 "bajada_broca≔p[0,0,-0.012,0,0,0]"
    global bajada_broca=p[0,0,-0.012,0,0,0]
    $ 398 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 399 "barreno_actual≔0"
    global barreno_actual=0
    $ 400 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 401 "Perforacion"
      $ 402 "MoveL"
      $ 403 "internos≔interpolate_pose(Linea2_C, Linea2_D, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea2_C_p, Linea2_D_p, barreno_actual/barrenos_menos1)
      $ 404 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 405 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 406 "bajada_broca≔p[0,0,-0.012,0,0,0]"
      global bajada_broca=p[0,0,-0.012,0,0,0]
      $ 407 "bajada≔p[0,0,0.012,0,0,0]"
      global bajada=p[0,0,0.012,0,0,0]
      $ 408 "Direction: Base Z-"
      global move_thread_flag_408=0
      thread move_thread_408():
        enter_critical
        move_thread_flag_408 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.045)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_408 = 2
        exit_critical
      end
      move_thread_flag_408 = 0
      move_thread_han_408 = run move_thread_408()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_408 > 1):
          join move_thread_han_408
          $ 409 "Until (distance)"
          break
        end
        sync()
      end
      $ 410 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 411 "Direction: Base Z+"
      global move_thread_flag_411=0
      thread move_thread_411():
        enter_critical
        move_thread_flag_411 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_411 = 2
        exit_critical
      end
      move_thread_flag_411 = 0
      move_thread_han_411 = run move_thread_411()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_411 > 1):
          join move_thread_han_411
          $ 412 "Until (distance)"
          break
        end
        sync()
      end
      $ 413 "Wait: 0.3"
      sleep(0.3)
      $ 414 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 415 "Wait: 0.3"
      sleep(0.3)
      $ 416 "Loop 2 times"
      Loop_36 = 0
      while (Loop_36 < 2):
        $ 417 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 418 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 419 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 420 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.005)
        $ 421 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_36 = Loop_36 + 1
      end
      $ 422 "Direction: Base Z+"
      global move_thread_flag_422=0
      thread move_thread_422():
        enter_critical
        move_thread_flag_422 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_422 = 2
        exit_critical
      end
      move_thread_flag_422 = 0
      move_thread_han_422 = run move_thread_422()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_422 > 1):
          join move_thread_han_422
          $ 423 "Until (distance)"
          break
        end
        sync()
      end
      $ 424 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 425 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 426 "Call Quitar_broca"
      Quitar_broca()
      $ 427 "Call Poner_broca"
      Poner_broca()
    end
    $ 428 "EF"
    $ 429 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 430 "bajada_broca≔p[0,0,-0.012,0,0,0]"
    global bajada_broca=p[0,0,-0.012,0,0,0]
    $ 431 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 432 "barreno_actual≔0"
    global barreno_actual=0
    $ 433 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 434 "Perforacion"
      $ 435 "MoveL"
      $ 436 "internos≔interpolate_pose(Linea2_E, Linea2_F, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea2_E_p, Linea2_F_p, barreno_actual/barrenos_menos1)
      $ 437 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 438 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 439 "bajada_broca≔p[0,0,-0.012,0,0,0]"
      global bajada_broca=p[0,0,-0.012,0,0,0]
      $ 440 "bajada≔p[0,0,0.012,0,0,0]"
      global bajada=p[0,0,0.012,0,0,0]
      $ 441 "Direction: Base Z-"
      global move_thread_flag_441=0
      thread move_thread_441():
        enter_critical
        move_thread_flag_441 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.045)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_441 = 2
        exit_critical
      end
      move_thread_flag_441 = 0
      move_thread_han_441 = run move_thread_441()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_441 > 1):
          join move_thread_han_441
          $ 442 "Until (distance)"
          break
        end
        sync()
      end
      $ 443 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 444 "Direction: Base Z+"
      global move_thread_flag_444=0
      thread move_thread_444():
        enter_critical
        move_thread_flag_444 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_444 = 2
        exit_critical
      end
      move_thread_flag_444 = 0
      move_thread_han_444 = run move_thread_444()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_444 > 1):
          join move_thread_han_444
          $ 445 "Until (distance)"
          break
        end
        sync()
      end
      $ 446 "Wait: 0.3"
      sleep(0.3)
      $ 447 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 448 "Wait: 0.3"
      sleep(0.3)
      $ 449 "Loop 2 times"
      Loop_38 = 0
      while (Loop_38 < 2):
        $ 450 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 451 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 452 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 453 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.005)
        $ 454 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_38 = Loop_38 + 1
      end
      $ 455 "Direction: Base Z+"
      global move_thread_flag_455=0
      thread move_thread_455():
        enter_critical
        move_thread_flag_455 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_455 = 2
        exit_critical
      end
      move_thread_flag_455 = 0
      move_thread_han_455 = run move_thread_455()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_455 > 1):
          join move_thread_han_455
          $ 456 "Until (distance)"
          break
        end
        sync()
      end
      $ 457 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 458 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 459 "If barreno_actual≥barrenos_menos1"
      if (barreno_actual >= barrenos_menos1):
        $ 460 "cambiar_broca≔ True "
        global cambiar_broca=  True  
      end
      $ 461 "Call Quitar_broca"
      Quitar_broca()
      $ 462 "Call Poner_broca"
      Poner_broca()
    end
    $ 463 "Popup: Linea2 con media Terminada!"
    popup("Linea2 con media Terminada!", "Mensaje", False, False, blocking=True)
    $ 464 "Broca_3"
    $ 465 "Linea1"
    $ 466 "Marcar_puntos"
    $ 467 "MoveL"
    $ 468 "Linea1_A" "breakAfter"
    movel(Linea1_A_p, a=0.5, v=0.1)
    $ 469 "Linea1_B" "breakAfter"
    movel(Linea1_B_p, a=0.5, v=0.1)
    $ 470 "Linea1_C" "breakAfter"
    movel(Linea1_C_p, a=0.5, v=0.1)
    $ 471 "Linea1_D" "breakAfter"
    movel(Linea1_D_p, a=0.5, v=0.1)
    $ 472 "Linea1_E" "breakAfter"
    movel(Linea1_E_p, a=0.5, v=0.1)
    $ 473 "Linea1_F" "breakAfter"
    movel(Linea1_F_p, a=0.5, v=0.1)
    $ 474 "AB"
    $ 475 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 476 "bajada_broca≔p[0,0,-0.012,0,0,0]"
    global bajada_broca=p[0,0,-0.012,0,0,0]
    $ 477 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 478 "barreno_actual≔0"
    global barreno_actual=0
    $ 479 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 480 "Perforacion"
      $ 481 "MoveL"
      $ 482 "internos≔interpolate_pose(Linea1_A, Linea1_B, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea1_A_p, Linea1_B_p, barreno_actual/barrenos_menos1)
      $ 483 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 484 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 485 "bajada_broca≔p[0,0,-0.012,0,0,0]"
      global bajada_broca=p[0,0,-0.012,0,0,0]
      $ 486 "bajada≔p[0,0,0.012,0,0,0]"
      global bajada=p[0,0,0.012,0,0,0]
      $ 487 "Direction: Base Z-"
      global move_thread_flag_487=0
      thread move_thread_487():
        enter_critical
        move_thread_flag_487 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.045)
        movel(towardsPos, a=0.015, v=0.01)
        move_thread_flag_487 = 2
        exit_critical
      end
      move_thread_flag_487 = 0
      move_thread_han_487 = run move_thread_487()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_487 > 1):
          join move_thread_han_487
          $ 488 "Until (distance)"
          break
        end
        sync()
      end
      $ 489 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 490 "Direction: Base Z+"
      global move_thread_flag_490=0
      thread move_thread_490():
        enter_critical
        move_thread_flag_490 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_490 = 2
        exit_critical
      end
      move_thread_flag_490 = 0
      move_thread_han_490 = run move_thread_490()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_490 > 1):
          join move_thread_han_490
          $ 491 "Until (distance)"
          break
        end
        sync()
      end
      $ 492 "Wait: 0.3"
      sleep(0.3)
      $ 493 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 494 "Wait: 0.3"
      sleep(0.3)
      $ 495 "Loop 2 times"
      Loop_18 = 0
      while (Loop_18 < 2):
        $ 496 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 497 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 498 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 499 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.005)
        $ 500 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_18 = Loop_18 + 1
      end
      $ 501 "Direction: Base Z+"
      global move_thread_flag_501=0
      thread move_thread_501():
        enter_critical
        move_thread_flag_501 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_501 = 2
        exit_critical
      end
      move_thread_flag_501 = 0
      move_thread_han_501 = run move_thread_501()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_501 > 1):
          join move_thread_han_501
          $ 502 "Until (distance)"
          break
        end
        sync()
      end
      $ 503 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 504 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 505 "Call Quitar_broca"
      Quitar_broca()
      $ 506 "Call Poner_broca"
      Poner_broca()
    end
    $ 507 "CD"
    $ 508 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 509 "bajada_broca≔p[0,0,-0.012,0,0,0]"
    global bajada_broca=p[0,0,-0.012,0,0,0]
    $ 510 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 511 "barreno_actual≔0"
    global barreno_actual=0
    $ 512 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 513 "Perforacion"
      $ 514 "MoveL"
      $ 515 "internos≔interpolate_pose(Linea1_C, Linea1_D, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea1_C_p, Linea1_D_p, barreno_actual/barrenos_menos1)
      $ 516 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 517 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 518 "bajada_broca≔p[0,0,-0.012,0,0,0]"
      global bajada_broca=p[0,0,-0.012,0,0,0]
      $ 519 "bajada≔p[0,0,0.012,0,0,0]"
      global bajada=p[0,0,0.012,0,0,0]
      $ 520 "Direction: Base Z-"
      global move_thread_flag_520=0
      thread move_thread_520():
        enter_critical
        move_thread_flag_520 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.045)
        movel(towardsPos, a=0.015, v=0.01)
        move_thread_flag_520 = 2
        exit_critical
      end
      move_thread_flag_520 = 0
      move_thread_han_520 = run move_thread_520()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_520 > 1):
          join move_thread_han_520
          $ 521 "Until (distance)"
          break
        end
        sync()
      end
      $ 522 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 523 "Direction: Base Z+"
      global move_thread_flag_523=0
      thread move_thread_523():
        enter_critical
        move_thread_flag_523 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_523 = 2
        exit_critical
      end
      move_thread_flag_523 = 0
      move_thread_han_523 = run move_thread_523()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_523 > 1):
          join move_thread_han_523
          $ 524 "Until (distance)"
          break
        end
        sync()
      end
      $ 525 "Wait: 0.3"
      sleep(0.3)
      $ 526 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 527 "Wait: 0.3"
      sleep(0.3)
      $ 528 "Loop 2 times"
      Loop_20 = 0
      while (Loop_20 < 2):
        $ 529 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 530 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 531 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 532 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.005)
        $ 533 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_20 = Loop_20 + 1
      end
      $ 534 "Direction: Base Z+"
      global move_thread_flag_534=0
      thread move_thread_534():
        enter_critical
        move_thread_flag_534 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_534 = 2
        exit_critical
      end
      move_thread_flag_534 = 0
      move_thread_han_534 = run move_thread_534()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_534 > 1):
          join move_thread_han_534
          $ 535 "Until (distance)"
          break
        end
        sync()
      end
      $ 536 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 537 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 538 "Call Quitar_broca"
      Quitar_broca()
      $ 539 "Call Poner_broca"
      Poner_broca()
    end
    $ 540 "EF"
    $ 541 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 542 "bajada_broca≔p[0,0,-0.012,0,0,0]"
    global bajada_broca=p[0,0,-0.012,0,0,0]
    $ 543 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 544 "barreno_actual≔0"
    global barreno_actual=0
    $ 545 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 546 "Perforacion"
      $ 547 "MoveL"
      $ 548 "internos≔interpolate_pose(Linea1_E, Linea1_F, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea1_E_p, Linea1_F_p, barreno_actual/barrenos_menos1)
      $ 549 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 550 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 551 "bajada_broca≔p[0,0,-0.012,0,0,0]"
      global bajada_broca=p[0,0,-0.012,0,0,0]
      $ 552 "bajada≔p[0,0,0.012,0,0,0]"
      global bajada=p[0,0,0.012,0,0,0]
      $ 553 "Direction: Base Z-"
      global move_thread_flag_553=0
      thread move_thread_553():
        enter_critical
        move_thread_flag_553 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.045)
        movel(towardsPos, a=0.015, v=0.01)
        move_thread_flag_553 = 2
        exit_critical
      end
      move_thread_flag_553 = 0
      move_thread_han_553 = run move_thread_553()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_553 > 1):
          join move_thread_han_553
          $ 554 "Until (distance)"
          break
        end
        sync()
      end
      $ 555 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 556 "Direction: Base Z+"
      global move_thread_flag_556=0
      thread move_thread_556():
        enter_critical
        move_thread_flag_556 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_556 = 2
        exit_critical
      end
      move_thread_flag_556 = 0
      move_thread_han_556 = run move_thread_556()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_556 > 1):
          join move_thread_han_556
          $ 557 "Until (distance)"
          break
        end
        sync()
      end
      $ 558 "Wait: 0.3"
      sleep(0.3)
      $ 559 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 560 "Wait: 0.3"
      sleep(0.3)
      $ 561 "Loop 2 times"
      Loop_22 = 0
      while (Loop_22 < 2):
        $ 562 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 563 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 564 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 565 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.005)
        $ 566 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_22 = Loop_22 + 1
      end
      $ 567 "Direction: Base Z+"
      global move_thread_flag_567=0
      thread move_thread_567():
        enter_critical
        move_thread_flag_567 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_567 = 2
        exit_critical
      end
      move_thread_flag_567 = 0
      move_thread_han_567 = run move_thread_567()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_567 > 1):
          join move_thread_han_567
          $ 568 "Until (distance)"
          break
        end
        sync()
      end
      $ 569 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 570 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 571 "Call Quitar_broca"
      Quitar_broca()
      $ 572 "Call Poner_broca"
      Poner_broca()
    end
    $ 573 "Popup: Linea1 con full Terminada!"
    popup("Linea1 con full Terminada!", "Mensaje", False, False, blocking=True)
    $ 574 "Linea2"
    $ 575 "Marcar_puntos"
    $ 576 "MoveL"
    $ 577 "Linea2_A" "breakAfter"
    movel(Linea2_A_p, a=0.5, v=0.1)
    $ 578 "Linea2_B" "breakAfter"
    movel(Linea2_B_p, a=0.5, v=0.1)
    $ 579 "Linea2_C" "breakAfter"
    movel(Linea2_C_p, a=0.5, v=0.1)
    $ 580 "Linea2_D" "breakAfter"
    movel(Linea2_D_p, a=0.5, v=0.1)
    $ 581 "Linea2_E" "breakAfter"
    movel(Linea2_E_p, a=0.5, v=0.1)
    $ 582 "Linea2_F" "breakAfter"
    movel(Linea2_F_p, a=0.5, v=0.1)
    $ 583 "AB"
    $ 584 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 585 "bajada_broca≔p[0,0,-0.012,0,0,0]"
    global bajada_broca=p[0,0,-0.012,0,0,0]
    $ 586 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 587 "barreno_actual≔0"
    global barreno_actual=0
    $ 588 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 589 "Perforacion"
      $ 590 "MoveL"
      $ 591 "internos≔interpolate_pose(Linea2_A, Linea2_B, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea2_A_p, Linea2_B_p, barreno_actual/barrenos_menos1)
      $ 592 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 593 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 594 "bajada_broca≔p[0,0,-0.012,0,0,0]"
      global bajada_broca=p[0,0,-0.012,0,0,0]
      $ 595 "bajada≔p[0,0,0.012,0,0,0]"
      global bajada=p[0,0,0.012,0,0,0]
      $ 596 "Direction: Base Z-"
      global move_thread_flag_596=0
      thread move_thread_596():
        enter_critical
        move_thread_flag_596 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.045)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_596 = 2
        exit_critical
      end
      move_thread_flag_596 = 0
      move_thread_han_596 = run move_thread_596()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_596 > 1):
          join move_thread_han_596
          $ 597 "Until (distance)"
          break
        end
        sync()
      end
      $ 598 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 599 "Direction: Base Z+"
      global move_thread_flag_599=0
      thread move_thread_599():
        enter_critical
        move_thread_flag_599 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_599 = 2
        exit_critical
      end
      move_thread_flag_599 = 0
      move_thread_han_599 = run move_thread_599()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_599 > 1):
          join move_thread_han_599
          $ 600 "Until (distance)"
          break
        end
        sync()
      end
      $ 601 "Wait: 0.3"
      sleep(0.3)
      $ 602 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 603 "Wait: 0.3"
      sleep(0.3)
      $ 604 "Loop 2 times"
      Loop_40 = 0
      while (Loop_40 < 2):
        $ 605 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 606 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 607 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 608 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.005)
        $ 609 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_40 = Loop_40 + 1
      end
      $ 610 "Direction: Base Z+"
      global move_thread_flag_610=0
      thread move_thread_610():
        enter_critical
        move_thread_flag_610 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_610 = 2
        exit_critical
      end
      move_thread_flag_610 = 0
      move_thread_han_610 = run move_thread_610()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_610 > 1):
          join move_thread_han_610
          $ 611 "Until (distance)"
          break
        end
        sync()
      end
      $ 612 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 613 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 614 "Call Quitar_broca"
      Quitar_broca()
      $ 615 "Call Poner_broca"
      Poner_broca()
    end
    $ 616 "CD"
    $ 617 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 618 "bajada_broca≔p[0,0,-0.012,0,0,0]"
    global bajada_broca=p[0,0,-0.012,0,0,0]
    $ 619 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 620 "barreno_actual≔0"
    global barreno_actual=0
    $ 621 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 622 "Perforacion"
      $ 623 "MoveL"
      $ 624 "internos≔interpolate_pose(Linea2_C, Linea2_D, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea2_C_p, Linea2_D_p, barreno_actual/barrenos_menos1)
      $ 625 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 626 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 627 "bajada_broca≔p[0,0,-0.012,0,0,0]"
      global bajada_broca=p[0,0,-0.012,0,0,0]
      $ 628 "bajada≔p[0,0,0.012,0,0,0]"
      global bajada=p[0,0,0.012,0,0,0]
      $ 629 "Direction: Base Z-"
      global move_thread_flag_629=0
      thread move_thread_629():
        enter_critical
        move_thread_flag_629 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.045)
        movel(towardsPos, a=0.025, v=0.02)
        move_thread_flag_629 = 2
        exit_critical
      end
      move_thread_flag_629 = 0
      move_thread_han_629 = run move_thread_629()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_629 > 1):
          join move_thread_han_629
          $ 630 "Until (distance)"
          break
        end
        sync()
      end
      $ 631 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 632 "Direction: Base Z+"
      global move_thread_flag_632=0
      thread move_thread_632():
        enter_critical
        move_thread_flag_632 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_632 = 2
        exit_critical
      end
      move_thread_flag_632 = 0
      move_thread_han_632 = run move_thread_632()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_632 > 1):
          join move_thread_han_632
          $ 633 "Until (distance)"
          break
        end
        sync()
      end
      $ 634 "Wait: 0.3"
      sleep(0.3)
      $ 635 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 636 "Wait: 0.3"
      sleep(0.3)
      $ 637 "Loop 2 times"
      Loop_42 = 0
      while (Loop_42 < 2):
        $ 638 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 639 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 640 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 641 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.005)
        $ 642 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_42 = Loop_42 + 1
      end
      $ 643 "Direction: Base Z+"
      global move_thread_flag_643=0
      thread move_thread_643():
        enter_critical
        move_thread_flag_643 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_643 = 2
        exit_critical
      end
      move_thread_flag_643 = 0
      move_thread_han_643 = run move_thread_643()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_643 > 1):
          join move_thread_han_643
          $ 644 "Until (distance)"
          break
        end
        sync()
      end
      $ 645 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 646 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 647 "Call Quitar_broca"
      Quitar_broca()
      $ 648 "Call Poner_broca"
      Poner_broca()
    end
    $ 649 "EF"
    $ 650 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 651 "bajada_broca≔p[0,0,-0.012,0,0,0]"
    global bajada_broca=p[0,0,-0.012,0,0,0]
    $ 652 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 653 "barreno_actual≔0"
    global barreno_actual=0
    $ 654 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 655 "Perforacion"
      $ 656 "MoveL"
      $ 657 "internos≔interpolate_pose(Linea2_E, Linea2_F, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea2_E_p, Linea2_F_p, barreno_actual/barrenos_menos1)
      $ 658 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 659 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 660 "bajada_broca≔p[0,0,-0.012,0,0,0]"
      global bajada_broca=p[0,0,-0.012,0,0,0]
      $ 661 "bajada≔p[0,0,0.012,0,0,0]"
      global bajada=p[0,0,0.012,0,0,0]
      $ 662 "Direction: Base Z-"
      global move_thread_flag_662=0
      thread move_thread_662():
        enter_critical
        move_thread_flag_662 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.045)
        movel(towardsPos, a=0.025, v=0.02)
        move_thread_flag_662 = 2
        exit_critical
      end
      move_thread_flag_662 = 0
      move_thread_han_662 = run move_thread_662()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_662 > 1):
          join move_thread_han_662
          $ 663 "Until (distance)"
          break
        end
        sync()
      end
      $ 664 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 665 "Direction: Base Z+"
      global move_thread_flag_665=0
      thread move_thread_665():
        enter_critical
        move_thread_flag_665 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_665 = 2
        exit_critical
      end
      move_thread_flag_665 = 0
      move_thread_han_665 = run move_thread_665()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_665 > 1):
          join move_thread_han_665
          $ 666 "Until (distance)"
          break
        end
        sync()
      end
      $ 667 "Wait: 0.3"
      sleep(0.3)
      $ 668 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 669 "Wait: 0.3"
      sleep(0.3)
      $ 670 "Loop 2 times"
      Loop_44 = 0
      while (Loop_44 < 2):
        $ 671 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 672 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 673 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 674 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.005)
        $ 675 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_44 = Loop_44 + 1
      end
      $ 676 "Direction: Base Z+"
      global move_thread_flag_676=0
      thread move_thread_676():
        enter_critical
        move_thread_flag_676 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_676 = 2
        exit_critical
      end
      move_thread_flag_676 = 0
      move_thread_han_676 = run move_thread_676()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_676 > 1):
          join move_thread_han_676
          $ 677 "Until (distance)"
          break
        end
        sync()
      end
      $ 678 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 679 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 680 "If barreno_actual≥barrenos_menos1"
      if (barreno_actual >= barrenos_menos1):
        $ 681 "cambiar_broca≔ True "
        global cambiar_broca=  True  
      end
      $ 682 "Call Quitar_broca"
      Quitar_broca()
      $ 683 "Call Poner_broca"
      Poner_broca()
    end
    $ 684 "Popup: Linea2 con full Terminada!"
    popup("Linea2 con full Terminada!", "Mensaje", False, False, blocking=True)
    $ 685 "Posicion3"
    $ 686 "eje7≔3"
    global eje7=3
    $ 687 "Broca_1"
    $ 688 "Linea3"
    $ 689 "Marcar_puntos"
    $ 690 "MoveL"
    $ 691 "Home3" "breakAfter"
    movel(Home3_p, a=0.5, v=0.1)
    $ 692 "Linea3_A" "breakAfter"
    movel(Linea3_A_p, a=0.5, v=0.1)
    $ 693 "Linea3_B" "breakAfter"
    movel(Linea3_B_p, a=0.5, v=0.1)
    $ 694 "Linea3_C" "breakAfter"
    movel(Linea3_C_p, a=0.5, v=0.1)
    $ 695 "Linea3_D" "breakAfter"
    movel(Linea3_D_p, a=0.5, v=0.1)
    $ 696 "Linea3_E" "breakAfter"
    movel(Linea3_E_p, a=0.5, v=0.1)
    $ 697 "Linea3_F" "breakAfter"
    movel(Linea3_F_p, a=0.5, v=0.1)
    $ 698 "AB"
    $ 699 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 700 "bajada_broca≔p[0,0,-0.008,0,0,0]"
    global bajada_broca=p[0,0,-0.008,0,0,0]
    $ 701 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 702 "barreno_actual≔0"
    global barreno_actual=0
    $ 703 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 704 "Perforacion"
      $ 705 "MoveL"
      $ 706 "internos≔interpolate_pose(Linea3_A, Linea3_B, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea3_A_p, Linea3_B_p, barreno_actual/barrenos_menos1)
      $ 707 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 708 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 709 "bajada_broca≔p[0,0,-0.008,0,0,0]"
      global bajada_broca=p[0,0,-0.008,0,0,0]
      $ 710 "bajada≔p[0,0,0.008,0,0,0]"
      global bajada=p[0,0,0.008,0,0,0]
      $ 711 "Direction: Base Z-"
      global move_thread_flag_711=0
      thread move_thread_711():
        enter_critical
        move_thread_flag_711 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.055)
        movel(towardsPos, a=0.015, v=0.02)
        move_thread_flag_711 = 2
        exit_critical
      end
      move_thread_flag_711 = 0
      move_thread_han_711 = run move_thread_711()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_711 > 1):
          join move_thread_han_711
          $ 712 "Until (distance)"
          break
        end
        sync()
      end
      $ 713 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 714 "Direction: Base Z+"
      global move_thread_flag_714=0
      thread move_thread_714():
        enter_critical
        move_thread_flag_714 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.002)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_714 = 2
        exit_critical
      end
      move_thread_flag_714 = 0
      move_thread_han_714 = run move_thread_714()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_714 > 1):
          join move_thread_han_714
          $ 715 "Until (distance)"
          break
        end
        sync()
      end
      $ 716 "Wait: 0.3"
      sleep(0.3)
      $ 717 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 718 "Wait: 0.3"
      sleep(0.3)
      $ 719 "Loop 3 times"
      Loop_3 = 0
      while (Loop_3 < 3):
        $ 720 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 721 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 722 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 723 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.01)
        $ 724 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_3 = Loop_3 + 1
      end
      $ 725 "Direction: Base Z+"
      global move_thread_flag_725=0
      thread move_thread_725():
        enter_critical
        move_thread_flag_725 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_725 = 2
        exit_critical
      end
      move_thread_flag_725 = 0
      move_thread_han_725 = run move_thread_725()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_725 > 1):
          join move_thread_han_725
          $ 726 "Until (distance)"
          break
        end
        sync()
      end
      $ 727 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 728 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
    end
    $ 731 "CD"
    $ 732 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 733 "bajada_broca≔p[0,0,-0.008,0,0,0]"
    global bajada_broca=p[0,0,-0.008,0,0,0]
    $ 734 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 735 "barreno_actual≔0"
    global barreno_actual=0
    $ 736 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 737 "Perforacion"
      $ 738 "MoveL"
      $ 739 "internos≔interpolate_pose(Linea3_C, Linea3_D, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea3_C_p, Linea3_D_p, barreno_actual/barrenos_menos1)
      $ 740 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 741 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 742 "bajada_broca≔p[0,0,-0.008,0,0,0]"
      global bajada_broca=p[0,0,-0.008,0,0,0]
      $ 743 "bajada≔p[0,0,0.008,0,0,0]"
      global bajada=p[0,0,0.008,0,0,0]
      $ 744 "Direction: Base Z-"
      global move_thread_flag_744=0
      thread move_thread_744():
        enter_critical
        move_thread_flag_744 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.055)
        movel(towardsPos, a=0.015, v=0.02)
        move_thread_flag_744 = 2
        exit_critical
      end
      move_thread_flag_744 = 0
      move_thread_han_744 = run move_thread_744()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_744 > 1):
          join move_thread_han_744
          $ 745 "Until (distance)"
          break
        end
        sync()
      end
      $ 746 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 747 "Direction: Base Z+"
      global move_thread_flag_747=0
      thread move_thread_747():
        enter_critical
        move_thread_flag_747 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.002)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_747 = 2
        exit_critical
      end
      move_thread_flag_747 = 0
      move_thread_han_747 = run move_thread_747()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_747 > 1):
          join move_thread_han_747
          $ 748 "Until (distance)"
          break
        end
        sync()
      end
      $ 749 "Wait: 0.3"
      sleep(0.3)
      $ 750 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 751 "Wait: 0.3"
      sleep(0.3)
      $ 752 "Loop 3 times"
      Loop_6 = 0
      while (Loop_6 < 3):
        $ 753 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 754 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 755 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 756 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.01)
        $ 757 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_6 = Loop_6 + 1
      end
      $ 758 "Direction: Base Z+"
      global move_thread_flag_758=0
      thread move_thread_758():
        enter_critical
        move_thread_flag_758 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_758 = 2
        exit_critical
      end
      move_thread_flag_758 = 0
      move_thread_han_758 = run move_thread_758()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_758 > 1):
          join move_thread_han_758
          $ 759 "Until (distance)"
          break
        end
        sync()
      end
      $ 760 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 761 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
    end
    $ 764 "EF"
    $ 765 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 766 "bajada_broca≔p[0,0,-0.008,0,0,0]"
    global bajada_broca=p[0,0,-0.008,0,0,0]
    $ 767 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 768 "barreno_actual≔0"
    global barreno_actual=0
    $ 769 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 770 "Perforacion"
      $ 771 "MoveL"
      $ 772 "internos≔interpolate_pose(Linea3_E, Linea3_F, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea3_E_p, Linea3_F_p, barreno_actual/barrenos_menos1)
      $ 773 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 774 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 775 "bajada_broca≔p[0,0,-0.008,0,0,0]"
      global bajada_broca=p[0,0,-0.008,0,0,0]
      $ 776 "bajada≔p[0,0,0.008,0,0,0]"
      global bajada=p[0,0,0.008,0,0,0]
      $ 777 "Direction: Base Z-"
      global move_thread_flag_777=0
      thread move_thread_777():
        enter_critical
        move_thread_flag_777 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.055)
        movel(towardsPos, a=0.015, v=0.02)
        move_thread_flag_777 = 2
        exit_critical
      end
      move_thread_flag_777 = 0
      move_thread_han_777 = run move_thread_777()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_777 > 1):
          join move_thread_han_777
          $ 778 "Until (distance)"
          break
        end
        sync()
      end
      $ 779 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 780 "Direction: Base Z+"
      global move_thread_flag_780=0
      thread move_thread_780():
        enter_critical
        move_thread_flag_780 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.002)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_780 = 2
        exit_critical
      end
      move_thread_flag_780 = 0
      move_thread_han_780 = run move_thread_780()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_780 > 1):
          join move_thread_han_780
          $ 781 "Until (distance)"
          break
        end
        sync()
      end
      $ 782 "Wait: 0.3"
      sleep(0.3)
      $ 783 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 784 "Wait: 0.3"
      sleep(0.3)
      $ 785 "Loop 3 times"
      Loop_8 = 0
      while (Loop_8 < 3):
        $ 786 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 787 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 788 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 789 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.01)
        $ 790 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_8 = Loop_8 + 1
      end
      $ 791 "Direction: Base Z+"
      global move_thread_flag_791=0
      thread move_thread_791():
        enter_critical
        move_thread_flag_791 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_791 = 2
        exit_critical
      end
      move_thread_flag_791 = 0
      move_thread_han_791 = run move_thread_791()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_791 > 1):
          join move_thread_han_791
          $ 792 "Until (distance)"
          break
        end
        sync()
      end
      $ 793 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 794 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
    end
    $ 797 "Popup: Linea3 con chica Terminada!"
    popup("Linea3 con chica Terminada!", "Mensaje", False, False, blocking=True)
    $ 798 "Linea4"
    $ 799 "Marcar_puntos"
    $ 800 "MoveL"
    $ 801 "Home3" "breakAfter"
    movel(Home3_p, a=0.5, v=0.1)
    $ 802 "Linea4_A" "breakAfter"
    movel(Linea4_A_p, a=0.5, v=0.1)
    $ 803 "Linea4_B" "breakAfter"
    movel(Linea4_B_p, a=0.5, v=0.1)
    $ 804 "Linea4_C" "breakAfter"
    movel(Linea4_C_p, a=0.5, v=0.1)
    $ 805 "Linea4_D" "breakAfter"
    movel(Linea4_D_p, a=0.5, v=0.1)
    $ 806 "Linea4_E" "breakAfter"
    movel(Linea4_E_p, a=0.5, v=0.1)
    $ 807 "Linea4_F" "breakAfter"
    movel(Linea4_F_p, a=0.5, v=0.1)
    $ 808 "AB"
    $ 809 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 810 "bajada_broca≔p[0,0,-0.008,0,0,0]"
    global bajada_broca=p[0,0,-0.008,0,0,0]
    $ 811 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 812 "barreno_actual≔0"
    global barreno_actual=0
    $ 813 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 814 "Perforacion"
      $ 815 "MoveL"
      $ 816 "internos≔interpolate_pose(Linea4_A, Linea4_B, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea4_A_p, Linea4_B_p, barreno_actual/barrenos_menos1)
      $ 817 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 818 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 819 "bajada_broca≔p[0,0,-0.008,0,0,0]"
      global bajada_broca=p[0,0,-0.008,0,0,0]
      $ 820 "bajada≔p[0,0,0.008,0,0,0]"
      global bajada=p[0,0,0.008,0,0,0]
      $ 821 "Direction: Base Z-"
      global move_thread_flag_821=0
      thread move_thread_821():
        enter_critical
        move_thread_flag_821 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.055)
        movel(towardsPos, a=0.015, v=0.02)
        move_thread_flag_821 = 2
        exit_critical
      end
      move_thread_flag_821 = 0
      move_thread_han_821 = run move_thread_821()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_821 > 1):
          join move_thread_han_821
          $ 822 "Until (distance)"
          break
        end
        sync()
      end
      $ 823 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 824 "Direction: Base Z+"
      global move_thread_flag_824=0
      thread move_thread_824():
        enter_critical
        move_thread_flag_824 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.002)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_824 = 2
        exit_critical
      end
      move_thread_flag_824 = 0
      move_thread_han_824 = run move_thread_824()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_824 > 1):
          join move_thread_han_824
          $ 825 "Until (distance)"
          break
        end
        sync()
      end
      $ 826 "Wait: 0.3"
      sleep(0.3)
      $ 827 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 828 "Wait: 0.3"
      sleep(0.3)
      $ 829 "Loop 3 times"
      Loop_12 = 0
      while (Loop_12 < 3):
        $ 830 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 831 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 832 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 833 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.01)
        $ 834 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_12 = Loop_12 + 1
      end
      $ 835 "Direction: Base Z+"
      global move_thread_flag_835=0
      thread move_thread_835():
        enter_critical
        move_thread_flag_835 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_835 = 2
        exit_critical
      end
      move_thread_flag_835 = 0
      move_thread_han_835 = run move_thread_835()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_835 > 1):
          join move_thread_han_835
          $ 836 "Until (distance)"
          break
        end
        sync()
      end
      $ 837 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 838 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
    end
    $ 841 "CD"
    $ 842 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 843 "bajada_broca≔p[0,0,-0.008,0,0,0]"
    global bajada_broca=p[0,0,-0.008,0,0,0]
    $ 844 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 845 "barreno_actual≔0"
    global barreno_actual=0
    $ 846 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 847 "Perforacion"
      $ 848 "MoveL"
      $ 849 "internos≔interpolate_pose(Linea4_C, Linea4_D, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea4_C_p, Linea4_D_p, barreno_actual/barrenos_menos1)
      $ 850 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 851 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 852 "bajada_broca≔p[0,0,-0.008,0,0,0]"
      global bajada_broca=p[0,0,-0.008,0,0,0]
      $ 853 "bajada≔p[0,0,0.008,0,0,0]"
      global bajada=p[0,0,0.008,0,0,0]
      $ 854 "Direction: Base Z-"
      global move_thread_flag_854=0
      thread move_thread_854():
        enter_critical
        move_thread_flag_854 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.055)
        movel(towardsPos, a=0.015, v=0.02)
        move_thread_flag_854 = 2
        exit_critical
      end
      move_thread_flag_854 = 0
      move_thread_han_854 = run move_thread_854()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_854 > 1):
          join move_thread_han_854
          $ 855 "Until (distance)"
          break
        end
        sync()
      end
      $ 856 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 857 "Direction: Base Z+"
      global move_thread_flag_857=0
      thread move_thread_857():
        enter_critical
        move_thread_flag_857 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.002)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_857 = 2
        exit_critical
      end
      move_thread_flag_857 = 0
      move_thread_han_857 = run move_thread_857()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_857 > 1):
          join move_thread_han_857
          $ 858 "Until (distance)"
          break
        end
        sync()
      end
      $ 859 "Wait: 0.3"
      sleep(0.3)
      $ 860 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 861 "Wait: 0.3"
      sleep(0.3)
      $ 862 "Loop 3 times"
      Loop_15 = 0
      while (Loop_15 < 3):
        $ 863 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 864 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 865 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 866 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.01)
        $ 867 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_15 = Loop_15 + 1
      end
      $ 868 "Direction: Base Z+"
      global move_thread_flag_868=0
      thread move_thread_868():
        enter_critical
        move_thread_flag_868 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_868 = 2
        exit_critical
      end
      move_thread_flag_868 = 0
      move_thread_han_868 = run move_thread_868()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_868 > 1):
          join move_thread_han_868
          $ 869 "Until (distance)"
          break
        end
        sync()
      end
      $ 870 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 871 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
    end
    $ 874 "EF"
    $ 875 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 876 "bajada_broca≔p[0,0,-0.008,0,0,0]"
    global bajada_broca=p[0,0,-0.008,0,0,0]
    $ 877 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 878 "barreno_actual≔0"
    global barreno_actual=0
    $ 879 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 880 "Perforacion"
      $ 881 "MoveL"
      $ 882 "internos≔interpolate_pose(Linea4_E, Linea4_F, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea4_E_p, Linea4_F_p, barreno_actual/barrenos_menos1)
      $ 883 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 884 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 885 "bajada_broca≔p[0,0,-0.008,0,0,0]"
      global bajada_broca=p[0,0,-0.008,0,0,0]
      $ 886 "bajada≔p[0,0,0.008,0,0,0]"
      global bajada=p[0,0,0.008,0,0,0]
      $ 887 "Direction: Base Z-"
      global move_thread_flag_887=0
      thread move_thread_887():
        enter_critical
        move_thread_flag_887 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.055)
        movel(towardsPos, a=0.015, v=0.02)
        move_thread_flag_887 = 2
        exit_critical
      end
      move_thread_flag_887 = 0
      move_thread_han_887 = run move_thread_887()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_887 > 1):
          join move_thread_han_887
          $ 888 "Until (distance)"
          break
        end
        sync()
      end
      $ 889 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 890 "Direction: Base Z+"
      global move_thread_flag_890=0
      thread move_thread_890():
        enter_critical
        move_thread_flag_890 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.002)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_890 = 2
        exit_critical
      end
      move_thread_flag_890 = 0
      move_thread_han_890 = run move_thread_890()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_890 > 1):
          join move_thread_han_890
          $ 891 "Until (distance)"
          break
        end
        sync()
      end
      $ 892 "Wait: 0.3"
      sleep(0.3)
      $ 893 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 894 "Wait: 0.3"
      sleep(0.3)
      $ 895 "Loop 3 times"
      Loop_19 = 0
      while (Loop_19 < 3):
        $ 896 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 897 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 898 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 899 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.01)
        $ 900 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_19 = Loop_19 + 1
      end
      $ 901 "Direction: Base Z+"
      global move_thread_flag_901=0
      thread move_thread_901():
        enter_critical
        move_thread_flag_901 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_901 = 2
        exit_critical
      end
      move_thread_flag_901 = 0
      move_thread_han_901 = run move_thread_901()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_901 > 1):
          join move_thread_han_901
          $ 902 "Until (distance)"
          break
        end
        sync()
      end
      $ 903 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 904 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 905 "If barreno_actual≥barrenos_menos1"
      if (barreno_actual >= barrenos_menos1):
        $ 906 "cambiar_broca≔ True "
        global cambiar_broca=  True  
      end
    end
    $ 909 "Popup: Linea4 con chica Terminada!"
    popup("Linea4 con chica Terminada!", "Mensaje", False, False, blocking=True)
    $ 910 "Broca_2"
    $ 911 "Linea3"
    $ 912 "Marcar_puntos"
    $ 913 "MoveL"
    $ 914 "Home3" "breakAfter"
    movel(Home3_p, a=0.5, v=0.1)
    $ 915 "Linea3_A" "breakAfter"
    movel(Linea3_A_p, a=0.5, v=0.1)
    $ 916 "Linea3_B" "breakAfter"
    movel(Linea3_B_p, a=0.5, v=0.1)
    $ 917 "Linea3_C" "breakAfter"
    movel(Linea3_C_p, a=0.5, v=0.1)
    $ 918 "Linea3_D" "breakAfter"
    movel(Linea3_D_p, a=0.5, v=0.1)
    $ 919 "Linea3_E" "breakAfter"
    movel(Linea3_E_p, a=0.5, v=0.1)
    $ 920 "Linea3_F" "breakAfter"
    movel(Linea3_F_p, a=0.5, v=0.1)
    $ 921 "AB"
    $ 922 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 923 "bajada_broca≔p[0,0,-0.012,0,0,0]"
    global bajada_broca=p[0,0,-0.012,0,0,0]
    $ 924 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 925 "barreno_actual≔0"
    global barreno_actual=0
    $ 926 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 927 "Perforacion"
      $ 928 "MoveL"
      $ 929 "internos≔interpolate_pose(Linea3_A, Linea3_B, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea3_A_p, Linea3_B_p, barreno_actual/barrenos_menos1)
      $ 930 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 931 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 932 "bajada_broca≔p[0,0,-0.012,0,0,0]"
      global bajada_broca=p[0,0,-0.012,0,0,0]
      $ 933 "bajada≔p[0,0,0.012,0,0,0]"
      global bajada=p[0,0,0.012,0,0,0]
      $ 934 "Direction: Base Z-"
      global move_thread_flag_934=0
      thread move_thread_934():
        enter_critical
        move_thread_flag_934 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.055)
        movel(towardsPos, a=0.015, v=0.02)
        move_thread_flag_934 = 2
        exit_critical
      end
      move_thread_flag_934 = 0
      move_thread_han_934 = run move_thread_934()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_934 > 1):
          join move_thread_han_934
          $ 935 "Until (distance)"
          break
        end
        sync()
      end
      $ 936 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 937 "Direction: Base Z+"
      global move_thread_flag_937=0
      thread move_thread_937():
        enter_critical
        move_thread_flag_937 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_937 = 2
        exit_critical
      end
      move_thread_flag_937 = 0
      move_thread_han_937 = run move_thread_937()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_937 > 1):
          join move_thread_han_937
          $ 938 "Until (distance)"
          break
        end
        sync()
      end
      $ 939 "Wait: 0.3"
      sleep(0.3)
      $ 940 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 941 "Wait: 0.3"
      sleep(0.3)
      $ 942 "Loop 2 times"
      Loop_23 = 0
      while (Loop_23 < 2):
        $ 943 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 944 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 945 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 946 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.01)
        $ 947 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_23 = Loop_23 + 1
      end
      $ 948 "Direction: Base Z+"
      global move_thread_flag_948=0
      thread move_thread_948():
        enter_critical
        move_thread_flag_948 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_948 = 2
        exit_critical
      end
      move_thread_flag_948 = 0
      move_thread_han_948 = run move_thread_948()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_948 > 1):
          join move_thread_han_948
          $ 949 "Until (distance)"
          break
        end
        sync()
      end
      $ 950 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 951 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
    end
    $ 954 "CD"
    $ 955 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 956 "bajada_broca≔p[0,0,-0.012,0,0,0]"
    global bajada_broca=p[0,0,-0.012,0,0,0]
    $ 957 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 958 "barreno_actual≔0"
    global barreno_actual=0
    $ 959 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 960 "Perforacion"
      $ 961 "MoveL"
      $ 962 "internos≔interpolate_pose(Linea3_C, Linea3_D, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea3_C_p, Linea3_D_p, barreno_actual/barrenos_menos1)
      $ 963 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 964 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 965 "bajada_broca≔p[0,0,-0.012,0,0,0]"
      global bajada_broca=p[0,0,-0.012,0,0,0]
      $ 966 "bajada≔p[0,0,0.012,0,0,0]"
      global bajada=p[0,0,0.012,0,0,0]
      $ 967 "Direction: Base Z-"
      global move_thread_flag_967=0
      thread move_thread_967():
        enter_critical
        move_thread_flag_967 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.055)
        movel(towardsPos, a=0.015, v=0.02)
        move_thread_flag_967 = 2
        exit_critical
      end
      move_thread_flag_967 = 0
      move_thread_han_967 = run move_thread_967()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_967 > 1):
          join move_thread_han_967
          $ 968 "Until (distance)"
          break
        end
        sync()
      end
      $ 969 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 970 "Direction: Base Z+"
      global move_thread_flag_970=0
      thread move_thread_970():
        enter_critical
        move_thread_flag_970 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_970 = 2
        exit_critical
      end
      move_thread_flag_970 = 0
      move_thread_han_970 = run move_thread_970()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_970 > 1):
          join move_thread_han_970
          $ 971 "Until (distance)"
          break
        end
        sync()
      end
      $ 972 "Wait: 0.3"
      sleep(0.3)
      $ 973 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 974 "Wait: 0.3"
      sleep(0.3)
      $ 975 "Loop 2 times"
      Loop_25 = 0
      while (Loop_25 < 2):
        $ 976 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 977 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 978 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 979 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.01)
        $ 980 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_25 = Loop_25 + 1
      end
      $ 981 "Direction: Base Z+"
      global move_thread_flag_981=0
      thread move_thread_981():
        enter_critical
        move_thread_flag_981 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_981 = 2
        exit_critical
      end
      move_thread_flag_981 = 0
      move_thread_han_981 = run move_thread_981()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_981 > 1):
          join move_thread_han_981
          $ 982 "Until (distance)"
          break
        end
        sync()
      end
      $ 983 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 984 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
    end
    $ 987 "EF"
    $ 988 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 989 "bajada_broca≔p[0,0,-0.012,0,0,0]"
    global bajada_broca=p[0,0,-0.012,0,0,0]
    $ 990 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 991 "barreno_actual≔0"
    global barreno_actual=0
    $ 992 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 993 "Perforacion"
      $ 994 "MoveL"
      $ 995 "internos≔interpolate_pose(Linea3_E, Linea3_F, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea3_E_p, Linea3_F_p, barreno_actual/barrenos_menos1)
      $ 996 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 997 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 998 "bajada_broca≔p[0,0,-0.012,0,0,0]"
      global bajada_broca=p[0,0,-0.012,0,0,0]
      $ 999 "bajada≔p[0,0,0.012,0,0,0]"
      global bajada=p[0,0,0.012,0,0,0]
      $ 1000 "Direction: Base Z-"
      global move_thread_flag_1000=0
      thread move_thread_1000():
        enter_critical
        move_thread_flag_1000 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.055)
        movel(towardsPos, a=0.015, v=0.02)
        move_thread_flag_1000 = 2
        exit_critical
      end
      move_thread_flag_1000 = 0
      move_thread_han_1000 = run move_thread_1000()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1000 > 1):
          join move_thread_han_1000
          $ 1001 "Until (distance)"
          break
        end
        sync()
      end
      $ 1002 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 1003 "Direction: Base Z+"
      global move_thread_flag_1003=0
      thread move_thread_1003():
        enter_critical
        move_thread_flag_1003 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_1003 = 2
        exit_critical
      end
      move_thread_flag_1003 = 0
      move_thread_han_1003 = run move_thread_1003()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1003 > 1):
          join move_thread_han_1003
          $ 1004 "Until (distance)"
          break
        end
        sync()
      end
      $ 1005 "Wait: 0.3"
      sleep(0.3)
      $ 1006 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 1007 "Wait: 0.3"
      sleep(0.3)
      $ 1008 "Loop 2 times"
      Loop_27 = 0
      while (Loop_27 < 2):
        $ 1009 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 1010 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 1011 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 1012 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.01)
        $ 1013 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_27 = Loop_27 + 1
      end
      $ 1014 "Direction: Base Z+"
      global move_thread_flag_1014=0
      thread move_thread_1014():
        enter_critical
        move_thread_flag_1014 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_1014 = 2
        exit_critical
      end
      move_thread_flag_1014 = 0
      move_thread_han_1014 = run move_thread_1014()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1014 > 1):
          join move_thread_han_1014
          $ 1015 "Until (distance)"
          break
        end
        sync()
      end
      $ 1016 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 1017 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
    end
    $ 1020 "Popup: Linea3 con media Terminada!"
    popup("Linea3 con media Terminada!", "Mensaje", False, False, blocking=True)
    $ 1021 "Linea4"
    $ 1022 "Marcar_puntos"
    $ 1023 "MoveL"
    $ 1024 "Home3" "breakAfter"
    movel(Home3_p, a=0.5, v=0.1)
    $ 1025 "Linea4_A" "breakAfter"
    movel(Linea4_A_p, a=0.5, v=0.1)
    $ 1026 "Linea4_B" "breakAfter"
    movel(Linea4_B_p, a=0.5, v=0.1)
    $ 1027 "Linea4_C" "breakAfter"
    movel(Linea4_C_p, a=0.5, v=0.1)
    $ 1028 "Linea4_D" "breakAfter"
    movel(Linea4_D_p, a=0.5, v=0.1)
    $ 1029 "Linea4_E" "breakAfter"
    movel(Linea4_E_p, a=0.5, v=0.1)
    $ 1030 "Linea4_F" "breakAfter"
    movel(Linea4_F_p, a=0.5, v=0.1)
    $ 1031 "AB"
    $ 1032 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 1033 "bajada_broca≔p[0,0,-0.012,0,0,0]"
    global bajada_broca=p[0,0,-0.012,0,0,0]
    $ 1034 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 1035 "barreno_actual≔0"
    global barreno_actual=0
    $ 1036 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 1037 "Perforacion"
      $ 1038 "MoveL"
      $ 1039 "internos≔interpolate_pose(Linea4_A, Linea4_B, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea4_A_p, Linea4_B_p, barreno_actual/barrenos_menos1)
      $ 1040 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 1041 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 1042 "bajada_broca≔p[0,0,-0.012,0,0,0]"
      global bajada_broca=p[0,0,-0.012,0,0,0]
      $ 1043 "bajada≔p[0,0,0.012,0,0,0]"
      global bajada=p[0,0,0.012,0,0,0]
      $ 1044 "Direction: Base Z-"
      global move_thread_flag_1044=0
      thread move_thread_1044():
        enter_critical
        move_thread_flag_1044 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.055)
        movel(towardsPos, a=0.015, v=0.02)
        move_thread_flag_1044 = 2
        exit_critical
      end
      move_thread_flag_1044 = 0
      move_thread_han_1044 = run move_thread_1044()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1044 > 1):
          join move_thread_han_1044
          $ 1045 "Until (distance)"
          break
        end
        sync()
      end
      $ 1046 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 1047 "Direction: Base Z+"
      global move_thread_flag_1047=0
      thread move_thread_1047():
        enter_critical
        move_thread_flag_1047 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_1047 = 2
        exit_critical
      end
      move_thread_flag_1047 = 0
      move_thread_han_1047 = run move_thread_1047()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1047 > 1):
          join move_thread_han_1047
          $ 1048 "Until (distance)"
          break
        end
        sync()
      end
      $ 1049 "Wait: 0.3"
      sleep(0.3)
      $ 1050 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 1051 "Wait: 0.3"
      sleep(0.3)
      $ 1052 "Loop 2 times"
      Loop_29 = 0
      while (Loop_29 < 2):
        $ 1053 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 1054 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 1055 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 1056 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.01)
        $ 1057 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_29 = Loop_29 + 1
      end
      $ 1058 "Direction: Base Z+"
      global move_thread_flag_1058=0
      thread move_thread_1058():
        enter_critical
        move_thread_flag_1058 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_1058 = 2
        exit_critical
      end
      move_thread_flag_1058 = 0
      move_thread_han_1058 = run move_thread_1058()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1058 > 1):
          join move_thread_han_1058
          $ 1059 "Until (distance)"
          break
        end
        sync()
      end
      $ 1060 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 1061 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
    end
    $ 1064 "CD"
    $ 1065 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 1066 "bajada_broca≔p[0,0,-0.012,0,0,0]"
    global bajada_broca=p[0,0,-0.012,0,0,0]
    $ 1067 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 1068 "barreno_actual≔0"
    global barreno_actual=0
    $ 1069 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 1070 "Perforacion"
      $ 1071 "MoveL"
      $ 1072 "internos≔interpolate_pose(Linea4_C, Linea4_D, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea4_C_p, Linea4_D_p, barreno_actual/barrenos_menos1)
      $ 1073 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 1074 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 1075 "bajada_broca≔p[0,0,-0.012,0,0,0]"
      global bajada_broca=p[0,0,-0.012,0,0,0]
      $ 1076 "bajada≔p[0,0,0.012,0,0,0]"
      global bajada=p[0,0,0.012,0,0,0]
      $ 1077 "Direction: Base Z-"
      global move_thread_flag_1077=0
      thread move_thread_1077():
        enter_critical
        move_thread_flag_1077 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.055)
        movel(towardsPos, a=0.015, v=0.02)
        move_thread_flag_1077 = 2
        exit_critical
      end
      move_thread_flag_1077 = 0
      move_thread_han_1077 = run move_thread_1077()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1077 > 1):
          join move_thread_han_1077
          $ 1078 "Until (distance)"
          break
        end
        sync()
      end
      $ 1079 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 1080 "Direction: Base Z+"
      global move_thread_flag_1080=0
      thread move_thread_1080():
        enter_critical
        move_thread_flag_1080 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_1080 = 2
        exit_critical
      end
      move_thread_flag_1080 = 0
      move_thread_han_1080 = run move_thread_1080()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1080 > 1):
          join move_thread_han_1080
          $ 1081 "Until (distance)"
          break
        end
        sync()
      end
      $ 1082 "Wait: 0.3"
      sleep(0.3)
      $ 1083 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 1084 "Wait: 0.3"
      sleep(0.3)
      $ 1085 "Loop 2 times"
      Loop_31 = 0
      while (Loop_31 < 2):
        $ 1086 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 1087 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 1088 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 1089 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.01)
        $ 1090 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_31 = Loop_31 + 1
      end
      $ 1091 "Direction: Base Z+"
      global move_thread_flag_1091=0
      thread move_thread_1091():
        enter_critical
        move_thread_flag_1091 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_1091 = 2
        exit_critical
      end
      move_thread_flag_1091 = 0
      move_thread_han_1091 = run move_thread_1091()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1091 > 1):
          join move_thread_han_1091
          $ 1092 "Until (distance)"
          break
        end
        sync()
      end
      $ 1093 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 1094 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
    end
    $ 1097 "EF"
    $ 1098 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 1099 "bajada_broca≔p[0,0,-0.012,0,0,0]"
    global bajada_broca=p[0,0,-0.012,0,0,0]
    $ 1100 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 1101 "barreno_actual≔0"
    global barreno_actual=0
    $ 1102 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 1103 "Perforacion"
      $ 1104 "MoveL"
      $ 1105 "internos≔interpolate_pose(Linea4_E, Linea4_F, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea4_E_p, Linea4_F_p, barreno_actual/barrenos_menos1)
      $ 1106 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 1107 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 1108 "bajada_broca≔p[0,0,-0.012,0,0,0]"
      global bajada_broca=p[0,0,-0.012,0,0,0]
      $ 1109 "bajada≔p[0,0,0.012,0,0,0]"
      global bajada=p[0,0,0.012,0,0,0]
      $ 1110 "Direction: Base Z-"
      global move_thread_flag_1110=0
      thread move_thread_1110():
        enter_critical
        move_thread_flag_1110 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.055)
        movel(towardsPos, a=0.015, v=0.02)
        move_thread_flag_1110 = 2
        exit_critical
      end
      move_thread_flag_1110 = 0
      move_thread_han_1110 = run move_thread_1110()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1110 > 1):
          join move_thread_han_1110
          $ 1111 "Until (distance)"
          break
        end
        sync()
      end
      $ 1112 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 1113 "Direction: Base Z+"
      global move_thread_flag_1113=0
      thread move_thread_1113():
        enter_critical
        move_thread_flag_1113 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_1113 = 2
        exit_critical
      end
      move_thread_flag_1113 = 0
      move_thread_han_1113 = run move_thread_1113()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1113 > 1):
          join move_thread_han_1113
          $ 1114 "Until (distance)"
          break
        end
        sync()
      end
      $ 1115 "Wait: 0.3"
      sleep(0.3)
      $ 1116 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 1117 "Wait: 0.3"
      sleep(0.3)
      $ 1118 "Loop 2 times"
      Loop_33 = 0
      while (Loop_33 < 2):
        $ 1119 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 1120 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 1121 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 1122 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.01)
        $ 1123 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_33 = Loop_33 + 1
      end
      $ 1124 "Direction: Base Z+"
      global move_thread_flag_1124=0
      thread move_thread_1124():
        enter_critical
        move_thread_flag_1124 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_1124 = 2
        exit_critical
      end
      move_thread_flag_1124 = 0
      move_thread_han_1124 = run move_thread_1124()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1124 > 1):
          join move_thread_han_1124
          $ 1125 "Until (distance)"
          break
        end
        sync()
      end
      $ 1126 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 1127 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 1128 "If barreno_actual≥barrenos_menos1"
      if (barreno_actual >= barrenos_menos1):
        $ 1129 "cambiar_broca≔ True "
        global cambiar_broca=  True  
      end
    end
    $ 1132 "Popup: Linea4 con media Terminada!"
    popup("Linea4 con media Terminada!", "Mensaje", False, False, blocking=True)
    $ 1133 "Broca_3"
    $ 1134 "Linea3"
    $ 1135 "Marcar_puntos"
    $ 1136 "MoveL"
    $ 1137 "Home3" "breakAfter"
    movel(Home3_p, a=0.5, v=0.1)
    $ 1138 "Linea3_A" "breakAfter"
    movel(Linea3_A_p, a=0.5, v=0.1)
    $ 1139 "Linea3_B" "breakAfter"
    movel(Linea3_B_p, a=0.5, v=0.1)
    $ 1140 "Linea3_C" "breakAfter"
    movel(Linea3_C_p, a=0.5, v=0.1)
    $ 1141 "Linea3_D" "breakAfter"
    movel(Linea3_D_p, a=0.5, v=0.1)
    $ 1142 "Linea3_E" "breakAfter"
    movel(Linea3_E_p, a=0.5, v=0.1)
    $ 1143 "Linea3_F" "breakAfter"
    movel(Linea3_F_p, a=0.5, v=0.1)
    $ 1144 "AB"
    $ 1145 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 1146 "bajada_broca≔p[0,0,-0.024,0,0,0]"
    global bajada_broca=p[0,0,-0.024,0,0,0]
    $ 1147 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 1148 "barreno_actual≔0"
    global barreno_actual=0
    $ 1149 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 1150 "Perforacion"
      $ 1151 "MoveL"
      $ 1152 "internos≔interpolate_pose(Linea3_A, Linea3_B, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea3_A_p, Linea3_B_p, barreno_actual/barrenos_menos1)
      $ 1153 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 1154 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 1155 "bajada_broca≔p[0,0,-0.024,0,0,0]"
      global bajada_broca=p[0,0,-0.024,0,0,0]
      $ 1156 "bajada≔p[0,0,0.024,0,0,0]"
      global bajada=p[0,0,0.024,0,0,0]
      $ 1157 "Direction: Base Z-"
      global move_thread_flag_1157=0
      thread move_thread_1157():
        enter_critical
        move_thread_flag_1157 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.055)
        movel(towardsPos, a=0.015, v=0.02)
        move_thread_flag_1157 = 2
        exit_critical
      end
      move_thread_flag_1157 = 0
      move_thread_han_1157 = run move_thread_1157()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1157 > 1):
          join move_thread_han_1157
          $ 1158 "Until (distance)"
          break
        end
        sync()
      end
      $ 1159 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 1160 "Direction: Base Z+"
      global move_thread_flag_1160=0
      thread move_thread_1160():
        enter_critical
        move_thread_flag_1160 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_1160 = 2
        exit_critical
      end
      move_thread_flag_1160 = 0
      move_thread_han_1160 = run move_thread_1160()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1160 > 1):
          join move_thread_han_1160
          $ 1161 "Until (distance)"
          break
        end
        sync()
      end
      $ 1162 "Wait: 0.3"
      sleep(0.3)
      $ 1163 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 1164 "Wait: 0.3"
      sleep(0.3)
      $ 1165 "Loop 1 times"
      Loop_37 = 0
      while (Loop_37 < 1):
        $ 1166 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 1167 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 1168 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 1169 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.01)
        $ 1170 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_37 = Loop_37 + 1
      end
      $ 1171 "Direction: Base Z+"
      global move_thread_flag_1171=0
      thread move_thread_1171():
        enter_critical
        move_thread_flag_1171 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_1171 = 2
        exit_critical
      end
      move_thread_flag_1171 = 0
      move_thread_han_1171 = run move_thread_1171()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1171 > 1):
          join move_thread_han_1171
          $ 1172 "Until (distance)"
          break
        end
        sync()
      end
      $ 1173 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 1174 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
    end
    $ 1177 "CD"
    $ 1178 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 1179 "bajada_broca≔p[0,0,-0.024,0,0,0]"
    global bajada_broca=p[0,0,-0.024,0,0,0]
    $ 1180 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 1181 "barreno_actual≔0"
    global barreno_actual=0
    $ 1182 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 1183 "Perforacion"
      $ 1184 "MoveL"
      $ 1185 "internos≔interpolate_pose(Linea3_C, Linea3_D, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea3_C_p, Linea3_D_p, barreno_actual/barrenos_menos1)
      $ 1186 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 1187 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 1188 "bajada_broca≔p[0,0,-0.024,0,0,0]"
      global bajada_broca=p[0,0,-0.024,0,0,0]
      $ 1189 "bajada≔p[0,0,0.024,0,0,0]"
      global bajada=p[0,0,0.024,0,0,0]
      $ 1190 "Direction: Base Z-"
      global move_thread_flag_1190=0
      thread move_thread_1190():
        enter_critical
        move_thread_flag_1190 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.055)
        movel(towardsPos, a=0.015, v=0.02)
        move_thread_flag_1190 = 2
        exit_critical
      end
      move_thread_flag_1190 = 0
      move_thread_han_1190 = run move_thread_1190()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1190 > 1):
          join move_thread_han_1190
          $ 1191 "Until (distance)"
          break
        end
        sync()
      end
      $ 1192 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 1193 "Direction: Base Z+"
      global move_thread_flag_1193=0
      thread move_thread_1193():
        enter_critical
        move_thread_flag_1193 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_1193 = 2
        exit_critical
      end
      move_thread_flag_1193 = 0
      move_thread_han_1193 = run move_thread_1193()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1193 > 1):
          join move_thread_han_1193
          $ 1194 "Until (distance)"
          break
        end
        sync()
      end
      $ 1195 "Wait: 0.3"
      sleep(0.3)
      $ 1196 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 1197 "Wait: 0.3"
      sleep(0.3)
      $ 1198 "Loop 1 times"
      Loop_41 = 0
      while (Loop_41 < 1):
        $ 1199 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 1200 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 1201 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 1202 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.01)
        $ 1203 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_41 = Loop_41 + 1
      end
      $ 1204 "Direction: Base Z+"
      global move_thread_flag_1204=0
      thread move_thread_1204():
        enter_critical
        move_thread_flag_1204 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_1204 = 2
        exit_critical
      end
      move_thread_flag_1204 = 0
      move_thread_han_1204 = run move_thread_1204()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1204 > 1):
          join move_thread_han_1204
          $ 1205 "Until (distance)"
          break
        end
        sync()
      end
      $ 1206 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 1207 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
    end
    $ 1210 "EF"
    $ 1211 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 1212 "bajada_broca≔p[0,0,-0.024,0,0,0]"
    global bajada_broca=p[0,0,-0.024,0,0,0]
    $ 1213 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 1214 "barreno_actual≔0"
    global barreno_actual=0
    $ 1215 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 1216 "Perforacion"
      $ 1217 "MoveL"
      $ 1218 "internos≔interpolate_pose(Linea3_E, Linea3_F, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea3_E_p, Linea3_F_p, barreno_actual/barrenos_menos1)
      $ 1219 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 1220 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 1221 "bajada_broca≔p[0,0,-0.024,0,0,0]"
      global bajada_broca=p[0,0,-0.024,0,0,0]
      $ 1222 "bajada≔p[0,0,0.024,0,0,0]"
      global bajada=p[0,0,0.024,0,0,0]
      $ 1223 "Direction: Base Z-"
      global move_thread_flag_1223=0
      thread move_thread_1223():
        enter_critical
        move_thread_flag_1223 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.055)
        movel(towardsPos, a=0.015, v=0.02)
        move_thread_flag_1223 = 2
        exit_critical
      end
      move_thread_flag_1223 = 0
      move_thread_han_1223 = run move_thread_1223()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1223 > 1):
          join move_thread_han_1223
          $ 1224 "Until (distance)"
          break
        end
        sync()
      end
      $ 1225 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 1226 "Direction: Base Z+"
      global move_thread_flag_1226=0
      thread move_thread_1226():
        enter_critical
        move_thread_flag_1226 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_1226 = 2
        exit_critical
      end
      move_thread_flag_1226 = 0
      move_thread_han_1226 = run move_thread_1226()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1226 > 1):
          join move_thread_han_1226
          $ 1227 "Until (distance)"
          break
        end
        sync()
      end
      $ 1228 "Wait: 0.3"
      sleep(0.3)
      $ 1229 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 1230 "Wait: 0.3"
      sleep(0.3)
      $ 1231 "Loop 1 times"
      Loop_45 = 0
      while (Loop_45 < 1):
        $ 1232 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 1233 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 1234 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 1235 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.01)
        $ 1236 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_45 = Loop_45 + 1
      end
      $ 1237 "Direction: Base Z+"
      global move_thread_flag_1237=0
      thread move_thread_1237():
        enter_critical
        move_thread_flag_1237 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_1237 = 2
        exit_critical
      end
      move_thread_flag_1237 = 0
      move_thread_han_1237 = run move_thread_1237()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1237 > 1):
          join move_thread_han_1237
          $ 1238 "Until (distance)"
          break
        end
        sync()
      end
      $ 1239 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 1240 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
    end
    $ 1243 "Popup: Linea3 con full Terminada!"
    popup("Linea3 con full Terminada!", "Mensaje", False, False, blocking=True)
    $ 1244 "Linea4"
    $ 1245 "Marcar_puntos"
    $ 1246 "MoveL"
    $ 1247 "Home3" "breakAfter"
    movel(Home3_p, a=0.5, v=0.1)
    $ 1248 "Linea4_A" "breakAfter"
    movel(Linea4_A_p, a=0.5, v=0.1)
    $ 1249 "Linea4_B" "breakAfter"
    movel(Linea4_B_p, a=0.5, v=0.1)
    $ 1250 "Linea4_C" "breakAfter"
    movel(Linea4_C_p, a=0.5, v=0.1)
    $ 1251 "Linea4_D" "breakAfter"
    movel(Linea4_D_p, a=0.5, v=0.1)
    $ 1252 "Linea4_E" "breakAfter"
    movel(Linea4_E_p, a=0.5, v=0.1)
    $ 1253 "Linea4_F" "breakAfter"
    movel(Linea4_F_p, a=0.5, v=0.1)
    $ 1254 "AB"
    $ 1255 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 1256 "bajada_broca≔p[0,0,-0.024,0,0,0]"
    global bajada_broca=p[0,0,-0.024,0,0,0]
    $ 1257 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 1258 "barreno_actual≔0"
    global barreno_actual=0
    $ 1259 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 1260 "Perforacion"
      $ 1261 "MoveL"
      $ 1262 "internos≔interpolate_pose(Linea4_A, Linea4_B, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea4_A_p, Linea4_B_p, barreno_actual/barrenos_menos1)
      $ 1263 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 1264 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 1265 "bajada_broca≔p[0,0,-0.024,0,0,0]"
      global bajada_broca=p[0,0,-0.024,0,0,0]
      $ 1266 "bajada≔p[0,0,0.024,0,0,0]"
      global bajada=p[0,0,0.024,0,0,0]
      $ 1267 "Direction: Base Z-"
      global move_thread_flag_1267=0
      thread move_thread_1267():
        enter_critical
        move_thread_flag_1267 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.055)
        movel(towardsPos, a=0.015, v=0.02)
        move_thread_flag_1267 = 2
        exit_critical
      end
      move_thread_flag_1267 = 0
      move_thread_han_1267 = run move_thread_1267()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1267 > 1):
          join move_thread_han_1267
          $ 1268 "Until (distance)"
          break
        end
        sync()
      end
      $ 1269 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 1270 "Direction: Base Z+"
      global move_thread_flag_1270=0
      thread move_thread_1270():
        enter_critical
        move_thread_flag_1270 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_1270 = 2
        exit_critical
      end
      move_thread_flag_1270 = 0
      move_thread_han_1270 = run move_thread_1270()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1270 > 1):
          join move_thread_han_1270
          $ 1271 "Until (distance)"
          break
        end
        sync()
      end
      $ 1272 "Wait: 0.3"
      sleep(0.3)
      $ 1273 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 1274 "Wait: 0.3"
      sleep(0.3)
      $ 1275 "Loop 1 times"
      Loop_49 = 0
      while (Loop_49 < 1):
        $ 1276 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 1277 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 1278 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 1279 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.01)
        $ 1280 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_49 = Loop_49 + 1
      end
      $ 1281 "Direction: Base Z+"
      global move_thread_flag_1281=0
      thread move_thread_1281():
        enter_critical
        move_thread_flag_1281 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_1281 = 2
        exit_critical
      end
      move_thread_flag_1281 = 0
      move_thread_han_1281 = run move_thread_1281()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1281 > 1):
          join move_thread_han_1281
          $ 1282 "Until (distance)"
          break
        end
        sync()
      end
      $ 1283 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 1284 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
    end
    $ 1287 "CD"
    $ 1288 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 1289 "bajada_broca≔p[0,0,-0.024,0,0,0]"
    global bajada_broca=p[0,0,-0.024,0,0,0]
    $ 1290 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 1291 "barreno_actual≔0"
    global barreno_actual=0
    $ 1292 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 1293 "Perforacion"
      $ 1294 "MoveL"
      $ 1295 "internos≔interpolate_pose(Linea4_C, Linea4_D, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea4_C_p, Linea4_D_p, barreno_actual/barrenos_menos1)
      $ 1296 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 1297 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 1298 "bajada_broca≔p[0,0,-0.024,0,0,0]"
      global bajada_broca=p[0,0,-0.024,0,0,0]
      $ 1299 "bajada≔p[0,0,0.024,0,0,0]"
      global bajada=p[0,0,0.024,0,0,0]
      $ 1300 "Direction: Base Z-"
      global move_thread_flag_1300=0
      thread move_thread_1300():
        enter_critical
        move_thread_flag_1300 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.055)
        movel(towardsPos, a=0.015, v=0.02)
        move_thread_flag_1300 = 2
        exit_critical
      end
      move_thread_flag_1300 = 0
      move_thread_han_1300 = run move_thread_1300()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1300 > 1):
          join move_thread_han_1300
          $ 1301 "Until (distance)"
          break
        end
        sync()
      end
      $ 1302 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 1303 "Direction: Base Z+"
      global move_thread_flag_1303=0
      thread move_thread_1303():
        enter_critical
        move_thread_flag_1303 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_1303 = 2
        exit_critical
      end
      move_thread_flag_1303 = 0
      move_thread_han_1303 = run move_thread_1303()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1303 > 1):
          join move_thread_han_1303
          $ 1304 "Until (distance)"
          break
        end
        sync()
      end
      $ 1305 "Wait: 0.3"
      sleep(0.3)
      $ 1306 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 1307 "Wait: 0.3"
      sleep(0.3)
      $ 1308 "Loop 1 times"
      Loop_52 = 0
      while (Loop_52 < 1):
        $ 1309 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 1310 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 1311 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 1312 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.01)
        $ 1313 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_52 = Loop_52 + 1
      end
      $ 1314 "Direction: Base Z+"
      global move_thread_flag_1314=0
      thread move_thread_1314():
        enter_critical
        move_thread_flag_1314 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_1314 = 2
        exit_critical
      end
      move_thread_flag_1314 = 0
      move_thread_han_1314 = run move_thread_1314()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1314 > 1):
          join move_thread_han_1314
          $ 1315 "Until (distance)"
          break
        end
        sync()
      end
      $ 1316 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 1317 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
    end
    $ 1320 "EF"
    $ 1321 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 1322 "bajada_broca≔p[0,0,-0.024,0,0,0]"
    global bajada_broca=p[0,0,-0.024,0,0,0]
    $ 1323 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 1324 "barreno_actual≔0"
    global barreno_actual=0
    $ 1325 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 1326 "Perforacion"
      $ 1327 "MoveL"
      $ 1328 "internos≔interpolate_pose(Linea4_E, Linea4_F, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea4_E_p, Linea4_F_p, barreno_actual/barrenos_menos1)
      $ 1329 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 1330 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 1331 "bajada_broca≔p[0,0,-0.024,0,0,0]"
      global bajada_broca=p[0,0,-0.024,0,0,0]
      $ 1332 "bajada≔p[0,0,0.024,0,0,0]"
      global bajada=p[0,0,0.024,0,0,0]
      $ 1333 "Direction: Base Z-"
      global move_thread_flag_1333=0
      thread move_thread_1333():
        enter_critical
        move_thread_flag_1333 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.055)
        movel(towardsPos, a=0.015, v=0.02)
        move_thread_flag_1333 = 2
        exit_critical
      end
      move_thread_flag_1333 = 0
      move_thread_han_1333 = run move_thread_1333()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1333 > 1):
          join move_thread_han_1333
          $ 1334 "Until (distance)"
          break
        end
        sync()
      end
      $ 1335 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 1336 "Direction: Base Z+"
      global move_thread_flag_1336=0
      thread move_thread_1336():
        enter_critical
        move_thread_flag_1336 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.001)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_1336 = 2
        exit_critical
      end
      move_thread_flag_1336 = 0
      move_thread_han_1336 = run move_thread_1336()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1336 > 1):
          join move_thread_han_1336
          $ 1337 "Until (distance)"
          break
        end
        sync()
      end
      $ 1338 "Wait: 0.3"
      sleep(0.3)
      $ 1339 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 1340 "Wait: 0.3"
      sleep(0.3)
      $ 1341 "Loop 1 times"
      Loop_54 = 0
      while (Loop_54 < 1):
        $ 1342 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 1343 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 1344 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 1345 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.01)
        $ 1346 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_54 = Loop_54 + 1
      end
      $ 1347 "Direction: Base Z+"
      global move_thread_flag_1347=0
      thread move_thread_1347():
        enter_critical
        move_thread_flag_1347 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_1347 = 2
        exit_critical
      end
      move_thread_flag_1347 = 0
      move_thread_han_1347 = run move_thread_1347()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1347 > 1):
          join move_thread_han_1347
          $ 1348 "Until (distance)"
          break
        end
        sync()
      end
      $ 1349 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 1350 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 1351 "If barreno_actual≥barrenos_menos1"
      if (barreno_actual >= barrenos_menos1):
        $ 1352 "cambiar_broca≔ True "
        global cambiar_broca=  True  
      end
    end
    $ 1355 "Popup: Linea4 con full Terminada!"
    popup("Linea4 con full Terminada!", "Mensaje", False, False, blocking=True)
    $ 1356 "720"
    $ 1357 "Broca_1"
    $ 1358 "Linea5"
    $ 1359 "Marcar_puntos"
    $ 1360 "MoveL"
    $ 1361 "Home3" "breakAfter"
    movel(Home3_p, a=0.5, v=0.1)
    $ 1362 "Linea5_A" "breakAfter"
    movel(Linea5_A_p, a=0.5, v=0.1)
    $ 1363 "Linea5_B" "breakAfter"
    movel(Linea5_B_p, a=0.5, v=0.1)
    $ 1364 "AB"
    $ 1365 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 1366 "bajada_broca≔p[0,0,-0.008,0,0,0]"
    global bajada_broca=p[0,0,-0.008,0,0,0]
    $ 1367 "barrenos_menos1≔19"
    global barrenos_menos1=19
    $ 1368 "barreno_actual≔0"
    global barreno_actual=0
    $ 1369 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 1370 "Perforacion"
      $ 1371 "MoveL"
      $ 1372 "internos≔interpolate_pose(Linea5_A, Linea5_B, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea5_A_p, Linea5_B_p, barreno_actual/barrenos_menos1)
      $ 1373 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 1374 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 1375 "bajada_broca≔p[0,0,-0.008,0,0,0]"
      global bajada_broca=p[0,0,-0.008,0,0,0]
      $ 1376 "bajada≔p[0,0,0.008,0,0,0]"
      global bajada=p[0,0,0.008,0,0,0]
      $ 1377 "Direction: Base Z-"
      global move_thread_flag_1377=0
      thread move_thread_1377():
        enter_critical
        move_thread_flag_1377 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 1000.0)
        movel(towardsPos, a=0.005, v=0.007)
        move_thread_flag_1377 = 2
        exit_critical
      end
      move_thread_flag_1377 = 0
      move_thread_han_1377 = run move_thread_1377()
      while (True):
        local targetTcpDirection=get_target_tcp_speed()
        local stepsToRetract=tool_contact(direction=targetTcpDirection)
        if (stepsToRetract > 0):
          kill move_thread_han_1377
          stopl(0.001)
          local backTrackMovement=get_actual_joint_positions_history(stepsToRetract)
          local contactPose=get_forward_kin(backTrackMovement)
          local posDir=[targetTcpDirection[0],targetTcpDirection[1],targetTcpDirection[2]]
          local retractTo=contactPose
          if (norm(posDir) > 1e-6):
            local normalizedPosDir=normalize(posDir)
            local additionalRetraction=p[normalizedPosDir[0] * 0.0, normalizedPosDir[1] * 0.0, normalizedPosDir[2] * 0.0, 0, 0, 0]
            retractTo = pose_sub(contactPose, additionalRetraction)
          end
          movel(retractTo, a=0.001, v=0.1)
          $ 1378 "Until (tool_contact_detection)"
          break
        end
        sync()
      end
      $ 1379 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 1391 "Direction: Base Z+"
      global move_thread_flag_1391=0
      thread move_thread_1391():
        enter_critical
        move_thread_flag_1391 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.15)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_1391 = 2
        exit_critical
      end
      move_thread_flag_1391 = 0
      move_thread_han_1391 = run move_thread_1391()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1391 > 1):
          join move_thread_han_1391
          $ 1392 "Until (distance)"
          break
        end
        sync()
      end
      $ 1393 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 1394 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
    end
    $ 1463 "Popup: Linea5 con chica Terminada!"
    popup("Linea5 con chica Terminada!", "Mensaje", False, False, blocking=True)
    $ 1464 "Linea6"
    $ 1465 "Marcar_puntos"
    $ 1466 "MoveL"
    $ 1467 "Home3" "breakAfter"
    movel(Home3_p, a=0.5, v=0.1)
    $ 1468 "Linea4_A" "breakAfter"
    movel(Linea4_A_p, a=0.5, v=0.1)
    $ 1469 "Linea4_B" "breakAfter"
    movel(Linea4_B_p, a=0.5, v=0.1)
    $ 1470 "Linea4_C" "breakAfter"
    movel(Linea4_C_p, a=0.5, v=0.1)
    $ 1471 "Linea4_D" "breakAfter"
    movel(Linea4_D_p, a=0.5, v=0.1)
    $ 1472 "Linea4_E" "breakAfter"
    movel(Linea4_E_p, a=0.5, v=0.1)
    $ 1473 "Linea4_F" "breakAfter"
    movel(Linea4_F_p, a=0.5, v=0.1)
    $ 1474 "AB"
    $ 1475 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 1476 "bajada_broca≔p[0,0,-0.008,0,0,0]"
    global bajada_broca=p[0,0,-0.008,0,0,0]
    $ 1477 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 1478 "barreno_actual≔0"
    global barreno_actual=0
    $ 1479 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 1480 "Perforacion"
      $ 1481 "MoveL"
      $ 1482 "internos≔interpolate_pose(Linea4_A, Linea4_B, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea4_A_p, Linea4_B_p, barreno_actual/barrenos_menos1)
      $ 1483 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 1484 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 1485 "bajada_broca≔p[0,0,-0.008,0,0,0]"
      global bajada_broca=p[0,0,-0.008,0,0,0]
      $ 1486 "bajada≔p[0,0,0.008,0,0,0]"
      global bajada=p[0,0,0.008,0,0,0]
      $ 1487 "Direction: Base Z-"
      global move_thread_flag_1487=0
      thread move_thread_1487():
        enter_critical
        move_thread_flag_1487 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.055)
        movel(towardsPos, a=0.015, v=0.02)
        move_thread_flag_1487 = 2
        exit_critical
      end
      move_thread_flag_1487 = 0
      move_thread_han_1487 = run move_thread_1487()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1487 > 1):
          join move_thread_han_1487
          $ 1488 "Until (distance)"
          break
        end
        sync()
      end
      $ 1489 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 1490 "Direction: Base Z+"
      global move_thread_flag_1490=0
      thread move_thread_1490():
        enter_critical
        move_thread_flag_1490 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.002)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_1490 = 2
        exit_critical
      end
      move_thread_flag_1490 = 0
      move_thread_han_1490 = run move_thread_1490()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1490 > 1):
          join move_thread_han_1490
          $ 1491 "Until (distance)"
          break
        end
        sync()
      end
      $ 1492 "Wait: 0.3"
      sleep(0.3)
      $ 1493 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 1494 "Wait: 0.3"
      sleep(0.3)
      $ 1495 "Loop 3 times"
      Loop_61 = 0
      while (Loop_61 < 3):
        $ 1496 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 1497 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 1498 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 1499 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.01)
        $ 1500 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_61 = Loop_61 + 1
      end
      $ 1501 "Direction: Base Z+"
      global move_thread_flag_1501=0
      thread move_thread_1501():
        enter_critical
        move_thread_flag_1501 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_1501 = 2
        exit_critical
      end
      move_thread_flag_1501 = 0
      move_thread_han_1501 = run move_thread_1501()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1501 > 1):
          join move_thread_han_1501
          $ 1502 "Until (distance)"
          break
        end
        sync()
      end
      $ 1503 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 1504 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
    end
    $ 1507 "CD"
    $ 1508 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 1509 "bajada_broca≔p[0,0,-0.008,0,0,0]"
    global bajada_broca=p[0,0,-0.008,0,0,0]
    $ 1510 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 1511 "barreno_actual≔0"
    global barreno_actual=0
    $ 1512 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 1513 "Perforacion"
      $ 1514 "MoveL"
      $ 1515 "internos≔interpolate_pose(Linea4_C, Linea4_D, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea4_C_p, Linea4_D_p, barreno_actual/barrenos_menos1)
      $ 1516 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 1517 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 1518 "bajada_broca≔p[0,0,-0.008,0,0,0]"
      global bajada_broca=p[0,0,-0.008,0,0,0]
      $ 1519 "bajada≔p[0,0,0.008,0,0,0]"
      global bajada=p[0,0,0.008,0,0,0]
      $ 1520 "Direction: Base Z-"
      global move_thread_flag_1520=0
      thread move_thread_1520():
        enter_critical
        move_thread_flag_1520 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.055)
        movel(towardsPos, a=0.015, v=0.02)
        move_thread_flag_1520 = 2
        exit_critical
      end
      move_thread_flag_1520 = 0
      move_thread_han_1520 = run move_thread_1520()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1520 > 1):
          join move_thread_han_1520
          $ 1521 "Until (distance)"
          break
        end
        sync()
      end
      $ 1522 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 1523 "Direction: Base Z+"
      global move_thread_flag_1523=0
      thread move_thread_1523():
        enter_critical
        move_thread_flag_1523 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.002)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_1523 = 2
        exit_critical
      end
      move_thread_flag_1523 = 0
      move_thread_han_1523 = run move_thread_1523()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1523 > 1):
          join move_thread_han_1523
          $ 1524 "Until (distance)"
          break
        end
        sync()
      end
      $ 1525 "Wait: 0.3"
      sleep(0.3)
      $ 1526 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 1527 "Wait: 0.3"
      sleep(0.3)
      $ 1528 "Loop 3 times"
      Loop_63 = 0
      while (Loop_63 < 3):
        $ 1529 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 1530 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 1531 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 1532 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.01)
        $ 1533 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_63 = Loop_63 + 1
      end
      $ 1534 "Direction: Base Z+"
      global move_thread_flag_1534=0
      thread move_thread_1534():
        enter_critical
        move_thread_flag_1534 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_1534 = 2
        exit_critical
      end
      move_thread_flag_1534 = 0
      move_thread_han_1534 = run move_thread_1534()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1534 > 1):
          join move_thread_han_1534
          $ 1535 "Until (distance)"
          break
        end
        sync()
      end
      $ 1536 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 1537 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
    end
    $ 1540 "EF"
    $ 1541 "'desbaste_inicial'"
    # 'desbaste_inicial'
    $ 1542 "bajada_broca≔p[0,0,-0.008,0,0,0]"
    global bajada_broca=p[0,0,-0.008,0,0,0]
    $ 1543 "barrenos_menos1≔8"
    global barrenos_menos1=8
    $ 1544 "barreno_actual≔0"
    global barreno_actual=0
    $ 1545 "Loop barreno_actual≤barrenos_menos1"
    while (barreno_actual <= barrenos_menos1):
      $ 1546 "Perforacion"
      $ 1547 "MoveL"
      $ 1548 "internos≔interpolate_pose(Linea4_E, Linea4_F, barreno_actual/barrenos_menos1)"
      global internos= interpolate_pose (Linea4_E_p, Linea4_F_p, barreno_actual/barrenos_menos1)
      $ 1549 "internos" "breakAfter"
      movel(internos, a=0.5, v=0.1)
      $ 1550 "'desbaste_inicial'"
      # 'desbaste_inicial'
      $ 1551 "bajada_broca≔p[0,0,-0.008,0,0,0]"
      global bajada_broca=p[0,0,-0.008,0,0,0]
      $ 1552 "bajada≔p[0,0,0.008,0,0,0]"
      global bajada=p[0,0,0.008,0,0,0]
      $ 1553 "Direction: Base Z-"
      global move_thread_flag_1553=0
      thread move_thread_1553():
        enter_critical
        move_thread_flag_1553 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.055)
        movel(towardsPos, a=0.015, v=0.02)
        move_thread_flag_1553 = 2
        exit_critical
      end
      move_thread_flag_1553 = 0
      move_thread_han_1553 = run move_thread_1553()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1553 > 1):
          join move_thread_han_1553
          $ 1554 "Until (distance)"
          break
        end
        sync()
      end
      $ 1555 "Popup: punto contacto alanzdo"
      popup("punto contacto alanzdo", "Mensaje", False, False, blocking=True)
      $ 1556 "Direction: Base Z+"
      global move_thread_flag_1556=0
      thread move_thread_1556():
        enter_critical
        move_thread_flag_1556 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.002)
        movel(towardsPos, a=0.005, v=0.003)
        move_thread_flag_1556 = 2
        exit_critical
      end
      move_thread_flag_1556 = 0
      move_thread_han_1556 = run move_thread_1556()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1556 > 1):
          join move_thread_han_1556
          $ 1557 "Until (distance)"
          break
        end
        sync()
      end
      $ 1558 "Wait: 0.3"
      sleep(0.3)
      $ 1559 "Set CO[1]=Encender"
      set_configurable_digital_out(1, True)
      $ 1560 "Wait: 0.3"
      sleep(0.3)
      $ 1561 "Loop 3 times"
      Loop_65 = 0
      while (Loop_65 < 3):
        $ 1562 "bajar≔pose_add(get_actual_tcp_pose(), bajada_broca)"
        global bajar= pose_add ( get_actual_tcp_pose (), bajada_broca)
        $ 1563 "bajar" "breakAfter"
        movel(bajar, a=0.005, v=0.001)
        $ 1564 "subir≔pose_sub(get_actual_tcp_pose(), bajada_broca)"
        global subir= pose_sub ( get_actual_tcp_pose (), bajada_broca)
        $ 1565 "subir" "breakAfter"
        movel(subir, a=0.01, v=0.01)
        $ 1566 "bajada_broca≔pose_sub(bajada_broca, bajada)"
        global bajada_broca= pose_sub (bajada_broca, bajada)
        Loop_65 = Loop_65 + 1
      end
      $ 1567 "Direction: Base Z+"
      global move_thread_flag_1567=0
      thread move_thread_1567():
        enter_critical
        move_thread_flag_1567 = 1
        local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 0.06)
        movel(towardsPos, a=0.035, v=0.03)
        move_thread_flag_1567 = 2
        exit_critical
      end
      move_thread_flag_1567 = 0
      move_thread_han_1567 = run move_thread_1567()
      while (True):
        sleep(1.0E-10)
        if (move_thread_flag_1567 > 1):
          join move_thread_han_1567
          $ 1568 "Until (distance)"
          break
        end
        sync()
      end
      $ 1569 "Set CO[1]=Apagar"
      set_configurable_digital_out(1, False)
      $ 1570 "barreno_actual≔barreno_actual+1"
      global barreno_actual=barreno_actual+1
      $ 1571 "If barreno_actual≥barrenos_menos1"
      if (barreno_actual >= barrenos_menos1):
        $ 1572 "cambiar_broca≔ True "
        global cambiar_broca=  True  
      end
    end
    $ 1575 "Popup: Linea6 con chica Terminada!"
    popup("Linea6 con chica Terminada!", "Mensaje", False, False, blocking=True)
    $ 1576 "'Subprogramas:'"
    # 'Subprogramas:'
  end
end
